### ISSUE TITLE
UndefinedConversionError on ruby 2.0.0-p594 & p598

### ISSUE THREAD

**Issue by jcoyne** [minimagick/minimagick#272]
When I do:

 MiniMagick::Image.read(source_content)

I get the following error:

```
     Failure/Error: subject.run
     Encoding::UndefinedConversionError:
       "\x87" from ASCII-8BIT to UTF-8
     # /home/travis/.rvm/gems/ruby-2.0.0-p594/gems/mini_magick-4.0.0/lib/mini_magick/image.rb:34:in `write'
     # /home/travis/.rvm/gems/ruby-2.0.0-p594/gems/mini_magick-4.0.0/lib/mini_magick/image.rb:34:in `copy_stream'
     # /home/travis/.rvm/gems/ruby-2.0.0-p594/gems/mini_magick-4.0.0/lib/mini_magick/image.rb:34:in `block in read'
     # /home/travis/.rvm/gems/ruby-2.0.0-p594/gems/mini_magick-4.0.0/lib/mini_magick/utilities.rb:29:in `block in tempfile'
     # /home/travis/.rvm/gems/ruby-2.0.0-p594/gems/mini_magick-4.0.0/lib/mini_magick/utilities.rb:27:in `tap'
     # /home/travis/.rvm/gems/ruby-2.0.0-p594/gems/mini_magick-4.0.0/lib/mini_magick/utilities.rb:27:in `tempfile'
     # /home/travis/.rvm/gems/ruby-2.0.0-p594/gems/mini_magick-4.0.0/lib/mini_magick/image.rb:110:in `create'
     # /home/travis/.rvm/gems/ruby-2.0.0-p594/gems/mini_magick-4.0.0/lib/mini_magick/image.rb:34:in `read'
```

**Comment by AvaelKross** [comment]
I met this issue and found that only files under 10kb were affected. This fix: http://stackoverflow.com/questions/10496874/why-does-openuri-treat-files-under-10kb-in-size-as-stringio saved my day and resolved this issue.

**Comment by uestcsp** [comment]
yes, this issues looks like it's bug from ruby, but i think minimagick can work around this issues as follow:
      OpenURI::Buffer.send :remove_const, 'StringMax' if OpenURI::Buffer.const_defined?('StringMax')
      OpenURI::Buffer.const_set 'StringMax', 0

**Comment by janko-m** [comment]
I would rather that people upgrade their ruby version.
