### ISSUE TITLE
Error on MiniMagick::Image.open(image.psd)

### ISSUE THREAD

**Issue by yogoo** [minimagick/minimagick#283]
Upon calling MiniMagick::Image.open(image.psd) from script, minimagick returns the following error.
I couldn't find the file identify tries to access. The identify command works fine on known existing files.

```
 Converting PSD file '~/.frameit/devices_frames/iPhone 5c/Blue/iPhone_5c_Horz_Blu_sRGB.psd'
/Library/Ruby/Gems/2.0.0/gems/mini_magick-3.8.1/lib/mini_magick/image.rb:441:in `run': Command ("identify -quiet -ping /var/folders/rz/6ndkt81d14q4vtx0cms979h40000gn/T/mini_magick20150117-5207-569mpj.psd") failed: {:status_code=>1, :output=>""} (MiniMagick::Error)
```
Trace:
```
    from /Library/Ruby/Gems/2.0.0/gems/mini_magick-3.8.1/lib/mini_magick/image.rb:423:in `run_command'
    from /Library/Ruby/Gems/2.0.0/gems/mini_magick-3.8.1/lib/mini_magick/image.rb:194:in `valid?'
    from /Library/Ruby/Gems/2.0.0/gems/mini_magick-3.8.1/lib/mini_magick/image.rb:149:in `create'
    from /Library/Ruby/Gems/2.0.0/gems/mini_magick-3.8.1/lib/mini_magick/image.rb:49:in `read'
    from /Library/Ruby/Gems/2.0.0/gems/mini_magick-3.8.1/lib/mini_magick/image.rb:117:in `block in open'
    from /Library/Ruby/Gems/2.0.0/gems/mini_magick-3.8.1/lib/mini_magick/image.rb:116:in `open'
    from /Library/Ruby/Gems/2.0.0/gems/mini_magick-3.8.1/lib/mini_magick/image.rb:116:in `open'
    from /Library/Ruby/Gems/2.0.0/gems/frameit-0.2.0/lib/frameit/frame_converter.rb:61:in `block in convert_frames'
    from /Library/Ruby/Gems/2.0.0/gems/frameit-0.2.0/lib/frameit/frame_converter.rb:57:in `each'
    from /Library/Ruby/Gems/2.0.0/gems/frameit-0.2.0/lib/frameit/frame_converter.rb:57:in `convert_frames'
    from /Library/Ruby/Gems/2.0.0/gems/frameit-0.2.0/lib/frameit/editor.rb:23:in `initialize'
    from /Library/Ruby/Gems/2.0.0/gems/frameit-0.2.0/bin/frameit:39:in `new'
    from /Library/Ruby/Gems/2.0.0/gems/frameit-0.2.0/bin/frameit:39:in `block (2 levels) in <top (required)>'
    from /Library/Ruby/Gems/2.0.0/gems/commander-4.2.1/lib/commander/command.rb:180:in `call'
    from /Library/Ruby/Gems/2.0.0/gems/commander-4.2.1/lib/commander/command.rb:180:in `call'
    from /Library/Ruby/Gems/2.0.0/gems/commander-4.2.1/lib/commander/command.rb:155:in `run'
    from /Library/Ruby/Gems/2.0.0/gems/commander-4.2.1/lib/commander/runner.rb:421:in `run_active_command'
    from /Library/Ruby/Gems/2.0.0/gems/commander-4.2.1/lib/commander/runner.rb:81:in `run!'
    from /Library/Ruby/Gems/2.0.0/gems/commander-4.2.1/lib/commander/delegates.rb:8:in `run!'
    from /Library/Ruby/Gems/2.0.0/gems/commander-4.2.1/lib/commander/import.rb:10:in `block in <top (required)>'
```

**Comment by janko-m** [comment]
Try upgrading to the latest version of MiniMagick, and tell me what error are you getting then.

**Comment by yogoo** [comment]
```
irb(main):003:0> require 'mini_magick'
=> true
irb(main):004:0> image = MiniMagick::Image.open("/Users/username/.frameit/devices_frames/iPhone\ 5c/Blue/iPhone_5c_Horz_Blu_sRGB.psd")
MiniMagick::Invalid: `identify /var/folders/rz/6ndkt81d14q4vtx0cms979h40000gn/T/mini_magick20150119-1056-15r6l6i.psd` failed with error:

	from /Library/Ruby/Gems/2.0.0/gems/mini_magick-4.0.2/lib/mini_magick/image.rb:200:in `rescue in validate!'
	from /Library/Ruby/Gems/2.0.0/gems/mini_magick-4.0.2/lib/mini_magick/image.rb:198:in `validate!'
	from /Library/Ruby/Gems/2.0.0/gems/mini_magick-4.0.2/lib/mini_magick/image.rb:113:in `block in create'
	from /Library/Ruby/Gems/2.0.0/gems/mini_magick-4.0.2/lib/mini_magick/image.rb:112:in `tap'
	from /Library/Ruby/Gems/2.0.0/gems/mini_magick-4.0.2/lib/mini_magick/image.rb:112:in `create'
	from /Library/Ruby/Gems/2.0.0/gems/mini_magick-4.0.2/lib/mini_magick/image.rb:34:in `read'
	from /Library/Ruby/Gems/2.0.0/gems/mini_magick-4.0.2/lib/mini_magick/image.rb:90:in `block in open'
	from /System/Library/Frameworks/Ruby.framework/Versions/2.0/usr/lib/ruby/2.0.0/open-uri.rb:36:in `open'
	from /System/Library/Frameworks/Ruby.framework/Versions/2.0/usr/lib/ruby/2.0.0/open-uri.rb:36:in `open'
	from /Library/Ruby/Gems/2.0.0/gems/mini_magick-4.0.2/lib/mini_magick/image.rb:89:in `open'
	from (irb):4
	from /usr/bin/irb:12:in `<main>'
```

**Comment by janko-m** [comment]
Apparently ImageMagick doesn't consider this PSD valid. However, ImageMagick could still be able to work with it normally (although it returns exit status 1 anyway), try if it works from the command-line. You can also try either of the following:

1. Try this first, and see if errors are raised during processing:
  ```rb
  MiniMagick.configure do |config|
    config.validate_on_create = false
    config.validate_on_write = false
  end
  ```
2. If the processing commands are still raising errors, you can completely disable them with:
  ```rb
  MiniMagick.configure do |config|
    config.whiny = false
  end
  ```

**Comment by yogoo** [comment]
With this config:
```ruby
MiniMagick.configure do |config|
  config.validate_on_create = false
end
```
the psd is converted and written to disk with no errors anymore. Thanks!
