### ISSUE TITLE
Iterating over multi-page PDF throws errors

### ISSUE THREAD

**Issue by Kris-LIBIS** [minimagick/minimagick#317]
@janko-m I'm currently trying the code you supplied as an example in #261, but when I run it I get errors like so:

```
[0.22s] identify /tmp/mini_magick20150730-28016-xtii6h.pdf
[0.01s] identify -format %m %w %h %b /tmp/mini_magick20150730-28016-xtii6h.pdf[0][0]
MiniMagick::Error: `identify -format %m %w %h %b /tmp/mini_magick20150730-28016-xtii6h.pdf[0][0]` failed with error:
identify: unable to open image `/tmp/mini_magick20150730-28016-xtii6h.pdf[0]': No such file or directory @ error/blob.c/OpenBlob/2709.

	from /home/kris/.rvm/gems/ruby-2.2.2@libis/gems/mini_magick-4.2.7/lib/mini_magick/shell.rb:22:in `run'
	from /home/kris/.rvm/gems/ruby-2.2.2@libis/gems/mini_magick-4.2.7/lib/mini_magick/tool.rb:92:in `call'
	from /home/kris/.rvm/gems/ruby-2.2.2@libis/gems/mini_magick-4.2.7/lib/mini_magick/tool.rb:53:in `new'
	from /home/kris/.rvm/gems/ruby-2.2.2@libis/gems/mini_magick-4.2.7/lib/mini_magick/image/info.rb:121:in `identify'
	from /home/kris/.rvm/gems/ruby-2.2.2@libis/gems/mini_magick-4.2.7/lib/mini_magick/image/info.rb:93:in `raw'
	from /home/kris/.rvm/gems/ruby-2.2.2@libis/gems/mini_magick-4.2.7/lib/mini_magick/image/info.rb:31:in `[]'
	from /home/kris/.rvm/gems/ruby-2.2.2@libis/gems/mini_magick-4.2.7/lib/mini_magick/image/info.rb:41:in `block in cheap_info'
	from /home/kris/.rvm/gems/ruby-2.2.2@libis/gems/mini_magick-4.2.7/lib/mini_magick/image/info.rb:40:in `fetch'
	from /home/kris/.rvm/gems/ruby-2.2.2@libis/gems/mini_magick-4.2.7/lib/mini_magick/image/info.rb:40:in `cheap_info'
	from /home/kris/.rvm/gems/ruby-2.2.2@libis/gems/mini_magick-4.2.7/lib/mini_magick/image/info.rb:15:in `[]'
	from /home/kris/.rvm/gems/ruby-2.2.2@libis/gems/mini_magick-4.2.7/lib/mini_magick/image.rb:127:in `block in attribute'
	from /home/kris/.rvm/gems/ruby-2.2.2@libis/gems/mini_magick-4.2.7/lib/mini_magick/image.rb:432:in `composite'
...
```

I could make it work with the following patch:

```ruby
module MiniMagick
  class Image
    class Info
      def initialize(path)
        @path = path
        @path += '[0]' unless path =~ /\[\d+\]$/
        @info = {}
      end
      def identify
        MiniMagick::Tool::Identify.new do |builder|
          yield builder if block_given?
          builder << @path
        end
      end
    end
  end
end
```

I don't know the minimagick code enough to validate is this fix makes sense. I can make a pull request and provide a test case if you think it makes sense. Please advise.

Regards,
Kris

**Comment by janko-m** [comment]
Yes, this seems to be a good fix, go ahead and make the PR :+1:

**Comment by Kris-LIBIS** [comment]
I will. But it'll have to wait until september as I'm about to leave on holidays.
