### ISSUE TITLE
Carrierwave: mini_magick_processing_error

### ISSUE THREAD

**Issue by Seybo** [minimagick/minimagick#396]
Hi, here is my problem again. I'm quite new to rails so I'm not sure it's all the information you need. Let me know if you need more.

This is is what I've got on image upload after adding these lines to `production.rb`. I've checked the image in development and it's uploading ok. Also other images give me the same error

```
  CarrierWave.configure do |config|
    config.ignore_integrity_errors = false
    config.ignore_processing_errors = false
    config.ignore_download_errors = false
  end
```

```
F, [2017-01-16T12:24:16.440695 #4225] FATAL -- : 
CarrierWave::ProcessingError (translation missing: en.errors.messages.mini_magick_processing_error):
  carrierwave (1.0.0.rc) lib/carrierwave/processing/mini_magick.rb:308:in `rescue in manipulate!'
  carrierwave (1.0.0.rc) lib/carrierwave/processing/mini_magick.rb:288:in `manipulate!'
  carrierwave (1.0.0.rc) lib/carrierwave/processing/mini_magick.rb:155:in `resize_to_fit'
  carrierwave (1.0.0.rc) lib/carrierwave/uploader/processing.rb:82:in `block in process!'
  carrierwave (1.0.0.rc) lib/carrierwave/uploader/processing.rb:74:in `each'
  carrierwave (1.0.0.rc) lib/carrierwave/uploader/processing.rb:74:in `process!'
  carrierwave (1.0.0.rc) lib/carrierwave/uploader/callbacks.rb:14:in `block in with_callbacks'
  carrierwave (1.0.0.rc) lib/carrierwave/uploader/callbacks.rb:14:in `each'
  carrierwave (1.0.0.rc) lib/carrierwave/uploader/callbacks.rb:14:in `with_callbacks'
  carrierwave (1.0.0.rc) lib/carrierwave/uploader/cache.rb:137:in `cache!'
  carrierwave (1.0.0.rc) lib/carrierwave/uploader/versions.rb:268:in `block in cache_versions!'
  carrierwave (1.0.0.rc) lib/carrierwave/uploader/versions.rb:266:in `each'
  carrierwave (1.0.0.rc) lib/carrierwave/uploader/versions.rb:266:in `cache_versions!'
  carrierwave (1.0.0.rc) lib/carrierwave/uploader/callbacks.rb:16:in `block in with_callbacks'
  carrierwave (1.0.0.rc) lib/carrierwave/uploader/callbacks.rb:16:in `each'
  carrierwave (1.0.0.rc) lib/carrierwave/uploader/callbacks.rb:16:in `with_callbacks'
  carrierwave (1.0.0.rc) lib/carrierwave/uploader/cache.rb:137:in `cache!'
  carrierwave (1.0.0.rc) lib/carrierwave/mounter.rb:44:in `block in cache'
  carrierwave (1.0.0.rc) lib/carrierwave/mounter.rb:42:in `map'
  carrierwave (1.0.0.rc) lib/carrierwave/mounter.rb:42:in `cache'
  carrierwave (1.0.0.rc) lib/carrierwave/mount.rb:146:in `image_file='
  carrierwave (1.0.0.rc) lib/carrierwave/orm/activerecord.rb:70:in `image_file='
  activerecord (4.2.7.1) lib/active_record/attribute_assignment.rb:54:in `public_send'
  activerecord (4.2.7.1) lib/active_record/attribute_assignment.rb:54:in `_assign_attribute'
  activerecord (4.2.7.1) lib/active_record/attribute_assignment.rb:41:in `block in assign_attributes'
  actionpack (4.2.7.1) lib/action_controller/metal/strong_parameters.rb:185:in `each_pair'
  actionpack (4.2.7.1) lib/action_controller/metal/strong_parameters.rb:185:in `each_pair'
  activerecord (4.2.7.1) lib/active_record/attribute_assignment.rb:35:in `assign_attributes'
  rails_admin (1.1.0) lib/rails_admin/adapters/active_record/abstract_object.rb:19:in `set_attributes'
  rails_admin (1.1.0) lib/rails_admin/config/actions/new.rb:38:in `block (2 levels) in <class:New>'

```

**Comment by janko-m** [comment]
Can you show the processing code? Because now I only know that you're using CarrierWave with MiniMagick, and that you're getting processing errors, but since other users are also using CarrierWave and MiniMagick with *no* errors, it's not possible for me to determine what is the issue.

**Comment by Seybo** [comment]
I see
But this code works on heroku and locally so... I thought it might be correct for sure. Here it is

```
class ImageUploader < CarrierWave::Uploader::Base
  include CarrierWave::MiniMagick

  if Rails.env.staging?
    storage :fog
  else
    storage :file
  end

  def store_dir
    "uploads/images/products/"
  end

  version :thumb do
    process resize_to_fit: [640, 480]
    # process quality: 50
  end

  version :medium do
    process resize_to_fit: [1280, 960]
    # process quality: 70
  end

  def extension_whitelist
    %w(jpg jpeg gif png)
  end

  def filename
    "#{model.product.code}_#{secure_token}.jpg" if original_filename
  end

  protected

  def secure_token
    var = :"@#{mounted_as}_secure_token"
    model.instance_variable_get(var) || model.instance_variable_set(var, SecureRandom.uuid)
  end
end
```

**Comment by janko-m** [comment]
Ok, so this code works locally and on Heroku, but not on production environment? In that case perhaps ImageMagick is not installed there? I'm just guessing, you need to ask the CarrierWave maintainers how to retrieve the MiniMagick error that was rescued.

But actually you can probably just rescue the `CarrierWave::ProcessingError` yourself, and then retrieve the original MiniMagick error by calling `#cause` on the error:

```rb
begin
  # code that calls CarrierWave
rescue CarrierWave::ProcessingError => error
  mini_magick_error = error.cause
  puts "#{minimagick_error.class}: #{minimagick_error.message}"
  puts minimagick_error.backtrace
end
```

**Comment by Seybo** [comment]
> In that case perhaps ImageMagick is not installed there?

I think it should be installed because these commands work: 

```
$ convert -version
Version: ImageMagick 6.8.9-9 Q16 x86_64 2016-11-29 http://www.imagemagick.org
Copyright: Copyright (C) 1999-2014 ImageMagick Studio LLC
Features: DPC Modules OpenMP
Delegates: bzlib cairo djvu fftw fontconfig freetype jbig jng jpeg lcms lqr ltdl lzma openexr pangocairo png rsvg tiff wmf x xml zlib
```

> But actually you can probably just rescue the CarrierWave::ProcessingError yourself, and then retrieve the original MiniMagick error by calling #cause on the error:

i think this code is somewhere inside rails admin which I'm uploading the picture from. So I don't know how to find it. Don't have enough skills yes

> you need to ask the CarrierWave maintainers how to retrieve the MiniMagick error that was rescued

ok, will try

**Comment by Seybo** [comment]
Ok, I just changed a couple of lines of code and moved to RMagick. And everything works with it. So I guess we can just close this issue unless you want to investigate it somehow and need my help with it.

**Comment by janko-m** [comment]
Nothing seems out of the ordinary in the processing code, so I don't think there is anything to investigate. I'll close this then.
