### ISSUE TITLE
JSON::ParserError

### ISSUE THREAD

**Issue by Silex** [minimagick/minimagick#410]
Hello,

`image.data` returns invalid JSON because of the `image.properties.comment` section that contains a newline.

I don't know if that's expected or not but I think it's not.

**EDIT**: this might be a bug in imagemagick

``` shell
root@f43afe0ce058:/srv/app# convert --version
Version: ImageMagick 6.8.9-9 Q16 x86_64 2017-03-12 http://www.imagemagick.org
```

``` irb
irb(main):010:0> m = MiniMagick::Image.open('http://hookedoneverything.com/wp-content/uploads/2015/04/panama-featured-iamge1-810x539.jpg')
=> #<MiniMagick::Image:0x000000122a47e0 @path="/tmp/mini_magick20170403-135-hws44.jpg", @tempfile=#<Tempfile:/tmp/mini_magick20170403-135-hws44.jpg (closed)>, @info=#<MiniMagick::Image::Info:0x000000122a47b8 @path="/tmp/mini_magick20170403-135-hws44.jpg", @info={}>>
irb(main):011:0> m.data
JSON::ParserError: 784: unexpected token at '{
  "image": {
    "name": "/tmp/mini_magick20170403-135-hws44.jpg[0]",
    "format": "JPEG",
    "formatDescription": "Joint Photographic Experts Group JFIF format",
    "mimeType": "image/jpeg",
    "class": "DirectClass",
    "geometry": {
      "width": "810",
      "height": "539",
      "x": "0",
      "y": "0"
    },
    "resolution": {
      "x": "96",
      "y": "96"
    },
    "printSize": {
      "x": "8.4375",
      "y": "5.6145833333333330373"
    },
    "units": "PixelsPerInch",
    "type": "TrueColor",
    "endianess": "Undefined",
    "colorspace": "sRGB",
    "depth": "8",
    "baseDepth": "8",
    "channelDepth": {
      "red": "8",
      "green": "8",
      "blue": "8"
    },
    "imageStatistics": {
      "all": {
        "min": "0",
        "max": "255",
        "mean": "133.878",
        "standardDeviation": "64.2895",
        "kurtosis": "0.182041",
        "skewness": "-0.403153"
      }
    },
    "channelStatistics": {
      "red": {
        "min": "0",
        "max": "255",
        "mean": "85.2965",
        "standardDeviation": "61.0873",
        "kurtosis": "-0.797503",
        "skewness": "0.256224"
      },
      "green": {
        "min": "0",
        "max": "255",
        "mean": "150.008",
        "standardDeviation": "63.9113",
        "kurtosis": "-1.07388",
        "skewness": "-0.407641"
      },
      "blue": {
        "min": "0",
        "max": "255",
        "mean": "166.328",
        "standardDeviation": "67.6988",
        "kurtosis": "-0.0426612",
        "skewness": "-0.957389"
      }
    },
    "renderingIntent": "Perceptual",
    "gamma": "0.454545",
    "chromaticity": {
      "redPrimary": {
        "x": "0.64",
        "y": "0.33"
      },
      "greenPrimary": {
        "x": "0.3",
        "y": "0.6"
      },
      "bluePrimary": {
        "x": "0.15",
        "y": "0.06"
      },
      "whitePrimary": {
        "x": "0.3127",
        "y": "0.329"
      }
    },
    "backgroundColor": "white",
    "borderColor": "srgb(223,223,223)",
    "matteColor": "grey74",
    "transparentColor": "black",
    "interlace": "None",
    "intensity": "Undefined",
    "compose": "Over",
    "pageGeometry": {
      "width": "810",
      "height": "539",
      "x": "0",
      "y": "0"
    },
    "dispose": "Undefined",
    "iterations": "0",
    "compression": "JPEG",
    "quality": "90",
    "orientation": "Undefined",
    "properties": {
      "comment": "CREATOR: gd-jpeg v1.0 (using IJG JPEG v80), quality = 90
",
      "date:create": "2017-04-03T14:41:14+02:00",
      "date:modify": "2017-04-03T14:41:14+02:00",
      "jpeg:colorspace": "2",
      "jpeg:sampling-factor": "2x2,1x1,1x1",
      "signature": "ec09863aa30940bc5565e2c64d2c96ec3adad6e46bb14324ccf2d132e7d83588"
    },
    "artifacts": {
      "filename": "/tmp/mini_magick20170403-135-hws44.jpg[0]"
    },
    "tainted": "False",
    "filesize": "140KB",
    "numberPixels": "437K",
    "pixelsPerSecond": "21.83MB",
    "userTime": "0.010u",
    "elapsedTime": "0:01.019",
    "version": "ImageMagick 6.8.9-9 Q16 x86_64 2017-03-12 http://www.imagemagick.org"
  }
}'
	from /usr/local/bundle/gems/json-1.8.6/lib/json/common.rb:155:in `parse'
	from /usr/local/bundle/gems/json-1.8.6/lib/json/common.rb:155:in `parse'
	from /usr/local/bundle/gems/mini_magick-4.6.1/lib/mini_magick/image/info.rb:163:in `data'
	from /usr/local/bundle/gems/mini_magick-4.6.1/lib/mini_magick/image/info.rb:33:in `[]'
	from /usr/local/bundle/gems/mini_magick-4.6.1/lib/mini_magick/image.rb:127:in `block in attribute'
	from (irb):11
	from /usr/local/bundle/gems/railties-4.2.8/lib/rails/commands/console.rb:110:in `start'
	from /usr/local/bundle/gems/railties-4.2.8/lib/rails/commands/console.rb:9:in `start'
	from /usr/local/bundle/gems/railties-4.2.8/lib/rails/commands/commands_tasks.rb:68:in `console'
	from /usr/local/bundle/gems/railties-4.2.8/lib/rails/commands/commands_tasks.rb:39:in `run_command!'
	from /usr/local/bundle/gems/railties-4.2.8/lib/rails/commands.rb:17:in `<top (required)>'
	from /srv/app/bin/rails:4:in `require'
	from /srv/app/bin/rails:4:in `<main>'
```

**Comment by janko-m** [comment]
If ImageMagick isn't generating valid JSON, then there isn't really anything that MiniMagick can do about it. I also received a JSON parsing error one GIF file, because there was one comma missing in the middle of the JSON data. Any errors with invalid JSON need to be fixed in ImageMagick itself.

**Comment by Silex** [comment]
Alright.
