### ISSUE TITLE
JSON::ParserError (unexpected token at ' ')

### ISSUE THREAD

**Issue by YMadane** [minimagick/minimagick#470]
I tried

```rb
require "mini_magick"
img_1 = MiniMagick::Image.open("/Users/yamadane/Desktop/Random/t1.png")
img_1.data
```

Some more json/image details:

```rb
# ...
 },
    "renderingIntent": "Perceptual",
    "gamma": 0.454545,
    "chromaticity": {
      "redPrimary": {
        "x": 0.64,
        "y": 0.33
      },
      "greenPrimary": {
        "x": 0.3,
        "y": 0.6
      },
      "bluePrimary": {
        "x": 0.15,
        "y": 0.06
      },
      "whitePrimary": {
        "x": 0.3127,
        "y": 0.329
      }
    },
    "matteColor": "#BDBDBD",
    "backgroundColor": "#FFFFFF",
    "borderColor": "#DFDFDF",
    "transparentColor": "#00000000",
    "interlace": "None",
    "intensity": "Undefined",
    "compose": "Over",
    "pageGeometry": {
      "width": 1275,
      "height": 1650,
      "x": 0,
      "y": 0
    },
    "dispose": "Undefined",
    "iterations": 0,
    "compression": "JPEG",
    "quality": 94,
    "orientation": "Undefined",
    "properties": {
      "date:create": "2018-10-15T12:56:20-05:00",
      "date:modify": "2018-10-15T12:56:20-05:00",
      "exif:ExifImageLength": "1650",
      "exif:ExifImageWidth": "1275",
      "exif:ExifOffset": "78",
      "exif:ResolutionUnit": "2",
      "exif:XResolution": "150/1",
      "exif:YResolution": "150/1",
      "jpeg:colorspace": "2",
      "jpeg:sampling-factor": "2x2,1x1,1x1",
      "signature": "d7b994f61727c9c009243068a15cf9f471054975385deeb0038adc289948f734"
    },
    "profiles": {
      "8bim": {
        "length": 40
      },
      "exif": {
        "length": 114
      },
      "icc": {
        "length": 560
      },
      "iptc": {
        "length": 0
      }
    },
    "tainted": false,
    "filesize": "49654B",
    "numberPixels": "2103750",
    "pixelsPerSecond": "42.075MB",
    "userTime": "0.050u",
    "elapsedTime": "0:01.049",
    "version": "/usr/local/Cellar/imagemagick/7.0.8-12/share/doc/ImageMagick-7//index.html"
  }
}
```

```
Traceback (most recent call last):
       16: from /Users/yamadane/.rbenv/versions/jruby-9.2.0.0/lib/ruby/gems/shared/gems/bundler-1.16.6/lib/bundler/cli.rb:424:in `exec'
       15: from /Users/yamadane/.rbenv/versions/jruby-9.2.0.0/lib/ruby/gems/shared/gems/bundler-1.16.6/lib/bundler/cli/exec.rb:28:in `run'
       14: from /Users/yamadane/.rbenv/versions/jruby-9.2.0.0/lib/ruby/gems/shared/gems/bundler-1.16.6/lib/bundler/cli/exec.rb:74:in `kernel_load'
       13: from /Users/yamadane/.rbenv/versions/jruby-9.2.0.0/lib/ruby/gems/shared/gems/bundler-1.16.6/lib/bundler/cli/exec.rb:1:in `(root)'
       12: from org/jruby/RubyKernel.java:994:in `load'
       11: from /Users/yamadane/.rbenv/versions/jruby-9.2.0.0/bin/irb:13:in `<main>'
       10: from org/jruby/RubyKernel.java:1180:in `catch'
        9: from org/jruby/RubyKernel.java:1180:in `catch'
        8: from org/jruby/RubyKernel.java:1418:in `loop'
        7: from org/jruby/RubyKernel.java:1037:in `eval'
        6: from (irb):7:in `<eval>'
        5: from /Users/yamadane/.rbenv/versions/jruby-9.2.0.0/lib/ruby/gems/shared/gems/mini_magick-4.9.2/lib/mini_magick/image.rb:132:in `block in data'
        4: from /Users/yamadane/.rbenv/versions/jruby-9.2.0.0/lib/ruby/gems/shared/gems/mini_magick-4.9.2/lib/mini_magick/image/info.rb:33:in `[]'
        3: from /Users/yamadane/.rbenv/versions/jruby-9.2.0.0/lib/ruby/gems/shared/gems/mini_magick-4.9.2/lib/mini_magick/image/info.rb:164:in `data'
        2: from /Users/yamadane/.rbenv/versions/jruby-9.2.0.0/lib/ruby/stdlib/json/common.rb:156:in `parse'
        1: from json/ext/Parser.java:236:in `parse'
JSON::ParserError (unexpected token at '')
irb(main):008:0> exit
```

**Comment by janko-m** [comment]
Could you share this image so that I can reproduce this locally? It seems that either ImageMagick is returning invalid JSON (which appears to happen too often), or Ruby's JSON parser isn't handling some edge case.

This could be checked by grabbing the JSON output and trying to `JSON.parse` it with Node.js:

```rb
# script.js
const { exec } = require('child_process')

exec('convert /Users/yamadane/Desktop/Random/t1.png json:', (err, stdout, stderr) => {
  const json = stdout.replace(/\n$/, '')

  console.log(JSON.parse(json))
})
```
```sh
$ node script.js
```

The JavaScript JSON parser implementation should probably be reviewed as the standard, so if it also fails, then it's indeed invalid JSON. If it succeeds, then the bug is in Ruby's `JSON` parser. In that case you could try parsing the output with either [Oj](https://github.com/ohler55/oj) or [yajl-ruby](https://github.com/brianmario/yajl-ruby) gems, and see if any of them parses the JSON correctly (and if not try to tweak their parsing options):

```rb
# script.rb
json = `convert /Users/yamadane/Desktop/Random/t1.png json:`.chomp("\n")

require "oj"
Oj.load(json)
# or
require "yajl"
yajl = Yajl::Parser.new
yajl.parse(json)
```
```sh
$ gem install oj yajl-ruby
$ ruby script.rb
```

I won't have time to figure this out, hopefully you now have enough information to try to figure it out yourself.

**Comment by YMadane** [comment]
This error was occurring when I was using jdk 10 . I guess minimagick jruby doesn't like java 10. It worked when I reverted to jdk 8.

Thanks
