### ISSUE TITLE
import_pixels appears to succeed, then throws error on next operation

### ISSUE THREAD

**Issue by ankane** [minimagick/minimagick#511]
Hi, thanks for this great library! Currently, `import_pixels` can fail but won't throw an error until a   next operation. The error message makes it look like an internal error in the next operation rather than an issue with the data passed to `import_pixels`.

Repro script:

```ruby
require "mini_magick"

bytes = "wz7BN\xF5{A\xA5\xEBxB\x9AC\xBEB\x10QHC\x8A\xADJC\xB5\x99>C!\x10MB=\xB1@C2\xB9\xECA\xAD\xA4\x9CB\xD8t\xAFB\a\x01|C\xCE\xAF\tCnq\x02C\x96$<Cr\x18\xEBB\xEEc(B\xEF\xC2.C\xF9\x99OA\xAB\xBD#B\x9Bs\xDCA\x16\xF9\xDEB\n*\x8CA\x92\xDFdC\x06\x8DfCT\\\xA6B\xC6\e\xF4B\xA2\x96\vC\x15\xEA\xAEBt\xEA<C\xE2\xD4'Be\x01\xB9B\xDE<>C/\xD5\xB2B\"\xC6\rBJ\x92$C]\xE7\xD1B\x0E\xC4XC\xFC0\x95B\x87\xD3\\B\xC8\xB3]C\x82x\x03C\xACj\xAEAs[wC\xAA\xAF/C@hOBQ-#Bs\x1A!CAf\x8EB\xE5\x0E\x19B$j\x1FC-\xA4;B\xC4v,C\xC9\x051A\xA2I\xE0?!\xCD\xBDA:\x81kA\x0F\xAB>C8\xB2\x8FB\x1F\xCE\x0ECp\x94\xBCB\x12\x9E\x16C\x80G\x93B\xE84\xBB@\x8E2iC+\x02\xCCB\xBEeSCz\x17<C\x91V\xC3A\xB4!oC~!H>\x12\xE0VCJ\x9E/B\x1C\x15rC\x19\x13\x02A;\xAA\x17A\r\xC1]C9-2CB,\xF7B\xDA?\x12Cq\xE4\x8DB^~\x10C\xBD\x9C\x8FB;m\x05C\xAEThC\xA2\xF4vC\x80\xFA\xD5B\x97\xDBRC8\xC9\xF0B?\xD6\xEBA|P\xF5Bt\x9C=C\x85cLC\xC4\x94UA\x02\x98\xB8A@\x0E\xB8B\xBE\x1F\x1FC\x10v#B\xE4u\xE1A\x05f\xE1B\x89\xFF&C\x94<\"C\x92\xF9IB\xC9\x06IA\xD7\x82[C\xDAegC\x84_/B\xF8\x9CnCw\xB3\xB7B Y\x89?`\xB5\x1AB\xBD`iCR\x1A\xFAB\"\x04HC*\xE0}C]L\xE8B\x1E\x8D\x8AB\xA1T\x84?A@/B\xCAp\x1DC?E\xEFB\xD1B\xBBBG\xCCE@\tyqC\x88`\xAFB7,\xF5Bb\xF8\xEBB\xFB\xEDbC^ivB,\xA9\x91A\x17\xB5\"B\x93q\xBCBe>*C\xE7\x8FICg`\bC\x1C\xDFYCu\x04OC\xB8\xC0\xEEB\xDC\xE8\x8DB{\xA75CmF\x9BBy\xCB\xEDB\x97a6C\v\xD3?C\x02aPC>>\vC-\xD9`C.\xE8\xCC@~\xA3\x98B_\xDF\x94B\xC3\x97fB]8%C\xED`0?\a'\xA8B\xB08\tC\xBFktCF\xCB\xD6@\xFF[\xC5B<\nmC\x10\xB1\xA9B\xCC\xF8\xF6Bd\xC3CC\xFE\x11\xD7B\b>(C\x99\xA9rC'\xE2`CR\x8CcA\x80q\x0EB\x88=zC\xA2\x18@C\xFF,\aB\xD1\xDB)CH\x12kCr\xF2!C\xAB\xE0\xC1@\xEF\x95\x02C\xF8y\xEEBH\xFB\xFABK{&C\xDE\xBA\xFEBj\b\x13C\tm\x11C\x1A\xAC4CV\xB3'B\x9Ci\x12CTJcC\xF0\x93yC\x1EE3C\x81\xF1\x99B\xCC\xB6fB\\S\xABB(lnC\xCE\x11\aBM\xB9\xD4B\xB0\xD6\x05C\xF7[!ATI\xECB\x88\x86\tB\xA1\x1D7B\xB1l\x06B]\x81;C}\x93\x1AC\xC9eWC\x98\xF2\x18B\x11r!B-\xCD\xEEB\x8A\xAFZCo\x8C#B'\xD0qC\xA5\x92bCL\xF7\x02C!\xF7\xB9B\xA0f\x93A\xC0\x92aCw\xB8\x1FCLyuC\xE4}\xEE@\x00$wCQMIB\x17\xE5\xA8BI\x1A\x0FB\xAA8\bB1-\xE9?\xBB\xF9\xE1B\x0EH\x97B\xBAS\xC1B\nb\xF1A\x03\xEF\x8CA\x80\xF6\xDCA\xCFL\x12C\xB2\xC5-Ca@CC\xA14dC\x02[\xB9B\x9E\x1FvC\x95\xE6\x1EB\xC5\xFCXC/\xD2#C \"yAC\atC\x89\n8CU5.C,D\x0FC\v\xC1\xF5B\x02\x1E\x9CBP\x1A\xDDB\xCF\x9C&C\xC7}lC\xF1\xE7\xDDB\xE7\xA6\xA8B\xC6Y'C\x85*\x9EA\xEA0\bC\x10\xB8dBa\x9E%C\"~9C\xFE\xB5ZCW\x92@@\xBEU2B\a\x1C\xD3B\\\xA6\xA7B\xC6\t\xE0Bv\x9DCCu\x86\xACB\xF7\xC0\x8AB\xFF5\xB4B#\x1E\xDDB\x987\xA6BU\xB2'Chu,C\x9F\x15hCO*\x82B8\xE0\x12C\xF8\xF9\x82B\xE4\x92[Cx\x8B\eC,\x84\x03B9\xEE>CF\xBA\xD8B\xFE\x96\x16C\xCDX6A\b\xED`C\xED\xEDxC\xA8\x1E\x80B\xF3#|C\x8D\xF76CE\x90IC\xB0\xED\x91B\x02n\x10C\xEE\xDC8B\xAA\xE1\"C\x1D8\x80BUv\xD9B\xE6\x04rCe[\xDDBZ\xA6lC]\xA5\xE0B\xD9\xAA\x1EC\xE0\xB3<C&\x10rC\xC0\x8C(B\xD0\xF9nC\xF0K\xD3B\xFANFC\xA9\xA4\xF2B\f\x1FVC}\xF9TCc_\xE9BJL\xD1@_f\x9DB\xF45VC\xA4\x16\xA6B\x8F\xA0zC\xEB2tCj\xA4BC\x06K\rC\x99}CC\xDEm\xB8A\xD2\x05#CJ\xA3\x93B\xA8]TC\xF4}\x96A%x\x92B\x91\x1E\xA2B\x84\x05UC\xA1\xBC9CLo\x94Bv\x19vC\x12\x9C\xC0A\x12\"\eB\xFATpB.Z-C\xE4P\x11C\xD5\xBF\xFCA\x12\xFD+B\x19G\xE5@\xF5\x97\vC\x9Fv\bC\xAC\xEC}C\xC0\x9D\xFDB\xBF\xECCC\xCE\x92\xF7A\xBE\xC2-C\xEDBdC\xF1\xD7BC\x85\xB5\xE3BM\x9F\xF7B\x8AM`C\xDEdoC\xAC/\xF3B\x9E\xF3\xF8>~\x1F\x06B\xE2R\xE6BF\x05ZB\xCB\xA2KC$-TC\x94\x93tB\t\xEB\x8AB\xFA\\\x88BU\x95^C\x92q\bC6\xF4,C\x1E\xB7\xC2B\xD5\x97\x1CB\x86\xE5\x93BPnqC\x91\x0F*C\xF2kkBl\x00lC\xC6\xB4\"A\xFFt\xD7A7jNCJw\xA6B\x18\xF4\x89AmL\x9DA\x12iqC\x12!IC\xD6\xE3\xC2A2\x8C\x98A3\xD1\x19BY\x81kAp\xDBFC\x8B\x87\"A\x11\xD5JC&\x91\xBDB~\x9CWC\x9Cc\xC8B\xE93aC\xC9\x02.C8\xED\x84Bi/TC\x97\xEA\xE7B/\x82\aC\x80\xEBtA,\x7F{C|\t+B\r`\xA1A\xEB\x94\x92@\xC4\xC4/A\x88\xCDXB\x00\xCC\x11A\xF8\xA2\x0EC{\xB9\xE9B\xFA\xFE\vC\x8D\xBENCz\xFF\x01C\xB3\xAFxCw?9C\x96\xC2\xB8B\xD1+\rC\xC5y\xE8B_\x11\x87A\xA6\xD3\xB1B\x8D\xF0\xCCBl\x81\xACB\xBE\xA9\x0FC}\xF9UC\x00\xBBtB\xB9\xD7\xD8B\x17\xC1yC}F\x0ECR\xDF4C;mKC!\xA7GC\x16\x90\nC\xA4\x19\xDFB!W+C\x98\xDD\xC1AgV}C\x04\x95hB\xC0\xDAcC\x1C\xFA\x86B\x16\xDB\nC\x97<\x19B\e\xB6 C)\xA7:Ckk\xFEB\x05}|B\xCA\xF7\fC\xF3\xF6+B>W\xDCB\xC6\x1A#C`\xED)CcPVC\x93\xAD\xC6@\xF9\x16$C\xC4\x01\xC0AoV\x85A\x10\xC1\x0FC\xC9i;@\x18\xAB\tB\xE4\xE8\xD7B\xCB\xB4\x01B\xDA)\x84B\xB0\x91\xD6Bul\x98B\xDA\xFA#C-7\xD1B\xA8\x8A\xD7A\xDF%\xCBB\xA9\xD91C-\xD3yC\xFE\x1E\rCu\xDF\x8AB\x87\x97JC\bY,Cz7cCk\x89qC\xB2\xB8\xFFB\xFF4VAVLOC\x9E#(C\xFBo\"CK\xB2\x04Bf\xE1\xF7B\xB7\xEF.C\xF3h\x19A9d\xF1B\xC6\xEC$CQ\xBA\xD3A\xE6;cC\xAF\x1F\x03Am(o?\x16lZC\x1D\xE8\xC3B\xE5\xBB\x19C\xE0b\xBFBp\xA7pC\xF7\xF1%CF\xF8mC\xA1\x0F\x1EC\xA0\xB5VC\xA2\xB3FC\t\v%C^\xE1\x1FBW\xD0dC\x13\xC1\x12C\xFA\x12\xD4B.\x03\xABB1\xF9/B\x03\rPB\xE9C\x1EB\xDC\xCAbC\xE9U[C\r\x8B\xA1Aq\xFB{A\xB1d\fC>\xB06C3\x973C\xFB\x86GC-RYB\x9A\x18\xF4@D*\x1CA\xAD\xAA\x1FC~\xB0\x82@\xCB\x88.C\xBC\xFFFC\x9E\x9DoC\xB9x6B\xCC\xB0hB\xF8'wC\x11T\xBEBn\x1E\x96@L\xB6\xE4B\x1F\xDE\xCCB\x7F)1C\x80\xBC\xD0B\xA8W+Ca\x96\"C\xEC\x05\x92A\x1C\xCD\xE1B\xB3-\xF3A\xF5\xA4\x92B\x02\xE2PC*\xCF)C`\rxC1\xD1KC$v<CM\x123C\x8Ck\x99Bu\x96\xDBB\xB2\x94\x0FC\xFA\xF1\xC6B)\xF2\fC\x9F>pC\n\xD2+C\e-XC#HiB@\xFA\xDDBS\xFB Cc7\x9DB\xA3\xA5yC\xB1.9B\xEDJAC+\xA1\x18B\x0FC\vC\xEF\x8AuB|yIB\xBB,]C\xA0C\x1DA\x86W0C;\xEC\xFABXW\xE0BlN\xD0B\xFCm\xA6B\xFEx\xB6AN\x828C\x9E\xDB\xA6@A\xCAjC\x9D\x81[C\x05\xF5TB\x19d6C\xCE\x99XC\x97\xD7]C\x12H\xA9BG\xA1\xDCB\x92j,C\xD6\xC7\x01C\xAB\x98\xD7B\xF5\x17\x9FB\x18c\x8FB\xAEs\xDBB\xCC\x14\rC\x89\xA9$B\xBAu\xF8A\xD3~\tB\xD5\x10\x86B\x02E|C\x16qiC|X\x9EBx\xC2\xE6B\xD1\x9D\xAFB,m\x0FC\x10_YB\xD8\x17>Ce\xA3xCn\\\x9EB&|VC\xE9\xE9sC*1mC\xB0\x83\x9EB\xAF\xFA:C~~\xA8BS\xA6dC-\x9BZCZ[\x1CC\xCA\xDE$CF\f\x0FAy\xAC_C\xB6\x0F\xDFB\x94\xDCYB3Q\eC_zFC\xA5\xE4VCf\eBBm\xB3\bC`tIC\xAF5\x00C\xBD\x8B3CY\xAApC\x90E\xE9B\x1E\xE1\xD1B\x8D\x8A\x04C=\xC7WA\xB2h8C\x03\xA8nC\x86M.C\xF6\xB6`C\xAF\xC0xC\xF3\xAD*Cq\xA1\x97BZX\nBE\xC6\x9DA\xE3\xE2xCH\xDD\xE5A\x91\x95|C\x93_\xFDB\x9F\xE5xA\xABM\xB6Bb+@C\t\xB7`C\xDC\xB2\x12C\x91\x82\xA8B\b\xD5\\B\xE5\x0FRC\v\xBBDC\x18\x84~C\xA1r\x14C\xE8S\x0FC|BZCG\x00\x1FC\e\x86NC\e\x9AZCb\xEDbB\x83}(C\xCA\xD3)BW\bbC\xF9\xA6\nC \xBA\x81A\xF7r\fC\xD7PkC\x1Eu\xFBB\xB3\xEA\x06Co5\xDCBr\xFB\nCy\xC9tC\v\t\xCAB\xCF\x85\xCF@\xD7\xDCWCh\x80NB\xB1\xA9\xC1B\xD2\xAE\x16C\x9D\x95$C\xFB\x94<Cf\x95\x12C\a\xDD\xAE@\xC8\x90\x8BA\xB8\x9F\xF4Bd%xC\xC4\xC5\xE5B\xC8\xC2WC\xF0\xFAvC\x82}\xC2B\x93\x8B;C\xC3\xDB(C\xEB\x8E\x10B\xF8J\bB\xCC\xF9\x06C\x93avB\xA1\xE4*C\xB3\x82\x1AB\xEC\"4C9G)C1W~C\x88\xEAaCv\xE4\vC\xC4\xB9{C3\x17YC\xD3\t\xECB\xBF\xDA\x1ACMWtC @\xA6A\xC5c|C:M\xC7B\xCB\xC4.C\x92\x19oC\xEE\xEFFCk\x9C\xFCAS\xCBBC\x92\x8B\xF8A}\x19\x15C\xE2\xC8\x90A^\xE8\xF4B\xE4\xD7'Cz\xB9iC\b\fFC\x9B\x15\xC6B\xC3\xC8\xDDB\xB4\x94\x93BM\xA3\xBBBW\xF1'B\x13Q\xF4A\x15WnC\x84d*C\f\x1A\x12C\xEF\xF7\xD5B>\xC0kC\x04(\rC\x19Z\x94Bi\xB9iA\xB7^\x04C\xD7\x1A@A9\xE9\fC\xB9\xA5mC=\x86\x17Cn\xA3\x8DB\x91\x95\x05Cg\xDE3C\xC0\xCE\x98B\x1Eq\tCe\x93\x8CA\xAA\a\eCD\xC6\x05C\xC0Q\xDAA\x13\a\xCEA\xF8\x1A]C#\xC1\xB4Bx\xA5\xADBs<\xA6B\xF1\xDF\x80B\x95\xBCWB\t\xFB*C\x9B\xB6JC=\xA9\xDAB\xB5USC\x82\xD9 B\xA0\xDC\xEFB\xE6%9C\x15\x17\xE6A\xF9\x12gB\x8B\xCA\bB\xE1/fC\xEC\x9B\xEAB\x06\xAC\x1CC\xF6\xDC\x82B\xE2\xBC\x0FC%#\x91B\x82r-C\xBF\xCEfCjn\x0EB\xF5\xE1hC\xB0\x00CCk\x03\x1DB\xF8\x15=B\x9AQfC\xD2\xACQCX~\xDFB\xB8\xAB$C\xF8\xED\xC6>\e\xA4KC\t<1B\xEF\xF5\eCb\xD4\xFBB"

# succeeds
img = MiniMagick::Image.import_pixels(bytes, 28, 28, 8, "gray")

# fails
img.to_blob
```

Traceback

```text
Traceback (most recent call last):
	2: from go.rb:11:in `<main>'
	1: from /Users/user/.rbenv/versions/2.7.1/lib/ruby/gems/2.7.0/gems/mini_magick-4.10.1/lib/mini_magick/image.rb:193:in `to_blob'
/Users/user/.rbenv/versions/2.7.1/lib/ruby/gems/2.7.0/gems/mini_magick-4.10.1/lib/mini_magick/image.rb:193:in `binread': No such file or directory @ rb_sysopen - /var/folders/g0/tw6m84v17bg4kf53c0x0yy340000gn/T/mini_magick20200501-31210-pjhz3b.png (Errno::ENOENT)
```

Related: #84

**Comment by janko** [comment]
Thanks for reporting. Yeah, this doesn't surprise me unfortunately. The `MiniMagick::Image` object does many different things, and it's not guaranteed methods will work with each other, especially the pixel-related ones.

Recently I've been playing with the idea of rewriting MiniMagick into a new gem, which would benefit from my current design knowledge, and would be a lot cleaner and immutable.

**Comment by ankane** [comment]
Hey @janko, thanks for the response (and sorry it took so long to follow up)! Will close this out, and keep an eye out for a potential sequel.
