### ISSUE TITLE
If you create a different version of the uploaded file, the assignment of params[:file] will fail.

### ISSUE THREAD

**Issue by Sakaki-Ya** [minimagick/minimagick#515]
[I asked carrierwave's Issue](https://github.com/carrierwaveuploader/carrierwave/issues/2486), but in hindsight I thought minimagick's Issue would be more appropriate, so let me ask you a question here.

```ruby
version :thumb do
    process resize_to_fit: [200, 200]
end
```
If you set the ```version``` in uploader.rb, ```user.avatar = params[:file]``` will fail.
The error message is as follows.
```
#<ArgumentError: wrong number of arguments (given 4, expected 2)>
```
Is there a way to resolve this error?  
What am I misunderstanding?

# Details

I am implementing an action to update the user's avatar.

```ruby
u = User.new
u.avatar = params[:file] # Assign a file like this, or
```

According to the above READEME code, I have set up the avatar update behavior as follows.

```ruby
class UsersController < ApplicationController
  def update
    user = User.find(params[:id])
    user.avatar = params[:file]
    render json: user
  end
  ...
end
```

uploader.rb is as follows.
```ruby
class ImageUploader < CarrierWave::Uploader::Base
  include CarrierWave::MiniMagick
  storage :file

  def store_dir
    "uploads/#{model.class.to_s.underscore}/#{mounted_as}/#{model.id}"
  end

  def default_url(*args)
    "/images/fallback/" + [version_name, "default.jpg"].compact.join('_')
  end

  version :thumb do
    process resize_to_fit: [200, 200]
  end
  ...
end
```

# Render JSON

- **Case of not creating a different version.**

```json
{
    "id": 1,
    "name": "foo",
    "avatar": {
        "url": "/uploads/tmp/0000-000-000-000/foo.jpg"
    },
}
```
The URL has changed to the path of the uploaded file.

- **Case to render JSON without assigning params[:filse] to avatar.**

```json
{
    "id": 1,
    "name": "foo",
    "avatar": {
        "url": "/images/fallback/default.jpg",
        "thumb": {
            "url": "/images/fallback/thumb_default.jpg"
        }
    },
}
```

**Comment by kaspergrubbe** [comment]
> #<ArgumentError: wrong number of arguments (given 4, expected 2)>

Could you provide us with a full stacktrace?

**Comment by Sakaki-Ya** [comment]
Thank you so much for taking the time to comment.
It's very long, but what follows is a complete stack trade.
```
{
    "status": 500,
    "error": "Internal Server Error",
    "exception": "#<ArgumentError: wrong number of arguments (given 4, expected 2)>",
    "traces": {
        "Application Trace": [
            {
                "exception_object_id": 69859332878140,
                "id": 25,
                "trace": "app/controllers/v1/users_controller.rb:18:in `update'"
            }
        ],
        "Framework Trace": [
            {
                "exception_object_id": 69859332878140,
                "id": 0,
                "trace": "carrierwave (2.1.0) lib/carrierwave/processing/mini_magick.rb:149:in `resize_to_fit'"
            },
            {
                "exception_object_id": 69859332878140,
                "id": 1,
                "trace": "carrierwave (2.1.0) lib/carrierwave/uploader/processing.rb:83:in `block (2 levels) in process!'"
            },
            {
                "exception_object_id": 69859332878140,
                "id": 2,
                "trace": "carrierwave (2.1.0) lib/carrierwave/uploader/processing.rb:75:in `each'"
            },
            {
                "exception_object_id": 69859332878140,
                "id": 3,
                "trace": "carrierwave (2.1.0) lib/carrierwave/uploader/processing.rb:75:in `block in process!'"
            },
            {
                "exception_object_id": 69859332878140,
                "id": 4,
                "trace": "carrierwave (2.1.0) lib/carrierwave/uploader/callbacks.rb:15:in `with_callbacks'"
            },
            {
                "exception_object_id": 69859332878140,
                "id": 5,
                "trace": "carrierwave (2.1.0) lib/carrierwave/uploader/processing.rb:74:in `process!'"
            },
            {
                "exception_object_id": 69859332878140,
                "id": 6,
                "trace": "carrierwave (2.1.0) lib/carrierwave/uploader/callbacks.rb:14:in `block in with_callbacks'"
            },
            {
                "exception_object_id": 69859332878140,
                "id": 7,
                "trace": "carrierwave (2.1.0) lib/carrierwave/uploader/callbacks.rb:14:in `each'"
            },
            {
                "exception_object_id": 69859332878140,
                "id": 8,
                "trace": "carrierwave (2.1.0) lib/carrierwave/uploader/callbacks.rb:14:in `with_callbacks'"
            },
            {
                "exception_object_id": 69859332878140,
                "id": 9,
                "trace": "carrierwave (2.1.0) lib/carrierwave/uploader/cache.rb:144:in `cache!'"
            },
            {
                "exception_object_id": 69859332878140,
                "id": 10,
                "trace": "carrierwave (2.1.0) lib/carrierwave/uploader/versions.rb:310:in `block in cache_versions!'"
            },
            {
                "exception_object_id": 69859332878140,
                "id": 11,
                "trace": "carrierwave (2.1.0) lib/carrierwave/uploader/versions.rb:308:in `each'"
            },
            {
                "exception_object_id": 69859332878140,
                "id": 12,
                "trace": "carrierwave (2.1.0) lib/carrierwave/uploader/versions.rb:308:in `cache_versions!'"
            },
            {
                "exception_object_id": 69859332878140,
                "id": 13,
                "trace": "carrierwave (2.1.0) lib/carrierwave/uploader/callbacks.rb:16:in `block in with_callbacks'"
            },
            {
                "exception_object_id": 69859332878140,
                "id": 14,
                "trace": "carrierwave (2.1.0) lib/carrierwave/uploader/callbacks.rb:16:in `each'"
            },
            {
                "exception_object_id": 69859332878140,
                "id": 15,
                "trace": "carrierwave (2.1.0) lib/carrierwave/uploader/callbacks.rb:16:in `with_callbacks'"
            },
            {
                "exception_object_id": 69859332878140,
                "id": 16,
                "trace": "carrierwave (2.1.0) lib/carrierwave/uploader/cache.rb:144:in `cache!'"
            },
            {
                "exception_object_id": 69859332878140,
                "id": 17,
                "trace": "carrierwave (2.1.0) lib/carrierwave/mounter.rb:63:in `block (2 levels) in cache'"
            },
            {
                "exception_object_id": 69859332878140,
                "id": 18,
                "trace": "carrierwave (2.1.0) lib/carrierwave/mounter.rb:176:in `handle_error'"
            },
            {
                "exception_object_id": 69859332878140,
                "id": 19,
                "trace": "carrierwave (2.1.0) lib/carrierwave/mounter.rb:47:in `block in cache'"
            },
            {
                "exception_object_id": 69859332878140,
                "id": 20,
                "trace": "carrierwave (2.1.0) lib/carrierwave/mounter.rb:46:in `map'"
            },
            {
                "exception_object_id": 69859332878140,
                "id": 21,
                "trace": "carrierwave (2.1.0) lib/carrierwave/mounter.rb:46:in `cache'"
            },
            {
                "exception_object_id": 69859332878140,
                "id": 22,
                "trace": "carrierwave (2.1.0) lib/carrierwave/mount.rb:146:in `avatar='"
            },
            {
                "exception_object_id": 69859332878140,
                "id": 23,
                "trace": "carrierwave (2.1.0) lib/carrierwave/mount.rb:373:in `avatar='"
            },
            {
                "exception_object_id": 69859332878140,
                "id": 24,
                "trace": "carrierwave (2.1.0) lib/carrierwave/orm/activerecord.rb:75:in `avatar='"
            },
            {
                "exception_object_id": 69859332878140,
                "id": 26,
                "trace": "actionpack (6.0.3.1) lib/action_controller/metal/basic_implicit_render.rb:6:in `send_action'"
            },
            {
                "exception_object_id": 69859332878140,
                "id": 27,
                "trace": "actionpack (6.0.3.1) lib/abstract_controller/base.rb:195:in `process_action'"
            },
            {
                "exception_object_id": 69859332878140,
                "id": 28,
                "trace": "actionpack (6.0.3.1) lib/action_controller/metal/rendering.rb:30:in `process_action'"
            },
            {
                "exception_object_id": 69859332878140,
                "id": 29,
                "trace": "actionpack (6.0.3.1) lib/abstract_controller/callbacks.rb:42:in `block in process_action'"
            },
            {
                "exception_object_id": 69859332878140,
                "id": 30,
                "trace": "activesupport (6.0.3.1) lib/active_support/callbacks.rb:135:in `run_callbacks'"
            },
            {
                "exception_object_id": 69859332878140,
                "id": 31,
                "trace": "actionpack (6.0.3.1) lib/abstract_controller/callbacks.rb:41:in `process_action'"
            },
            {
                "exception_object_id": 69859332878140,
                "id": 32,
                "trace": "actionpack (6.0.3.1) lib/action_controller/metal/rescue.rb:22:in `process_action'"
            },
            {
                "exception_object_id": 69859332878140,
                "id": 33,
                "trace": "actionpack (6.0.3.1) lib/action_controller/metal/instrumentation.rb:33:in `block in process_action'"
            },
            {
                "exception_object_id": 69859332878140,
                "id": 34,
                "trace": "activesupport (6.0.3.1) lib/active_support/notifications.rb:180:in `block in instrument'"
            },
            {
                "exception_object_id": 69859332878140,
                "id": 35,
                "trace": "activesupport (6.0.3.1) lib/active_support/notifications/instrumenter.rb:24:in `instrument'"
            },
            {
                "exception_object_id": 69859332878140,
                "id": 36,
                "trace": "activesupport (6.0.3.1) lib/active_support/notifications.rb:180:in `instrument'"
            },
            {
                "exception_object_id": 69859332878140,
                "id": 37,
                "trace": "actionpack (6.0.3.1) lib/action_controller/metal/instrumentation.rb:32:in `process_action'"
            },
            {
                "exception_object_id": 69859332878140,
                "id": 38,
                "trace": "actionpack (6.0.3.1) lib/action_controller/metal/params_wrapper.rb:245:in `process_action'"
            },
            {
                "exception_object_id": 69859332878140,
                "id": 39,
                "trace": "activerecord (6.0.3.1) lib/active_record/railties/controller_runtime.rb:27:in `process_action'"
            },
            {
                "exception_object_id": 69859332878140,
                "id": 40,
                "trace": "actionpack (6.0.3.1) lib/abstract_controller/base.rb:136:in `process'"
            },
            {
                "exception_object_id": 69859332878140,
                "id": 41,
                "trace": "actionpack (6.0.3.1) lib/action_controller/metal.rb:190:in `dispatch'"
            },
            {
                "exception_object_id": 69859332878140,
                "id": 42,
                "trace": "actionpack (6.0.3.1) lib/action_controller/metal.rb:254:in `dispatch'"
            },
            {
                "exception_object_id": 69859332878140,
                "id": 43,
                "trace": "actionpack (6.0.3.1) lib/action_dispatch/routing/route_set.rb:50:in `dispatch'"
            },
            {
                "exception_object_id": 69859332878140,
                "id": 44,
                "trace": "actionpack (6.0.3.1) lib/action_dispatch/routing/route_set.rb:33:in `serve'"
            },
            {
                "exception_object_id": 69859332878140,
                "id": 45,
                "trace": "actionpack (6.0.3.1) lib/action_dispatch/journey/router.rb:49:in `block in serve'"
            },
            {
                "exception_object_id": 69859332878140,
                "id": 46,
                "trace": "actionpack (6.0.3.1) lib/action_dispatch/journey/router.rb:32:in `each'"
            },
            {
                "exception_object_id": 69859332878140,
                "id": 47,
                "trace": "actionpack (6.0.3.1) lib/action_dispatch/journey/router.rb:32:in `serve'"
            },
            {
                "exception_object_id": 69859332878140,
                "id": 48,
                "trace": "actionpack (6.0.3.1) lib/action_dispatch/routing/route_set.rb:834:in `call'"
            },
            {
                "exception_object_id": 69859332878140,
                "id": 49,
                "trace": "rack (2.2.2) lib/rack/etag.rb:27:in `call'"
            },
            {
                "exception_object_id": 69859332878140,
                "id": 50,
                "trace": "rack (2.2.2) lib/rack/conditional_get.rb:40:in `call'"
            },
            {
                "exception_object_id": 69859332878140,
                "id": 51,
                "trace": "rack (2.2.2) lib/rack/head.rb:12:in `call'"
            },
            {
                "exception_object_id": 69859332878140,
                "id": 52,
                "trace": "activerecord (6.0.3.1) lib/active_record/migration.rb:567:in `call'"
            },
            {
                "exception_object_id": 69859332878140,
                "id": 53,
                "trace": "actionpack (6.0.3.1) lib/action_dispatch/middleware/callbacks.rb:27:in `block in call'"
            },
            {
                "exception_object_id": 69859332878140,
                "id": 54,
                "trace": "activesupport (6.0.3.1) lib/active_support/callbacks.rb:101:in `run_callbacks'"
            },
            {
                "exception_object_id": 69859332878140,
                "id": 55,
                "trace": "actionpack (6.0.3.1) lib/action_dispatch/middleware/callbacks.rb:26:in `call'"
            },
            {
                "exception_object_id": 69859332878140,
                "id": 56,
                "trace": "actionpack (6.0.3.1) lib/action_dispatch/middleware/executor.rb:14:in `call'"
            },
            {
                "exception_object_id": 69859332878140,
                "id": 57,
                "trace": "actionpack (6.0.3.1) lib/action_dispatch/middleware/actionable_exceptions.rb:17:in `call'"
            },
            {
                "exception_object_id": 69859332878140,
                "id": 58,
                "trace": "actionpack (6.0.3.1) lib/action_dispatch/middleware/debug_exceptions.rb:32:in `call'"
            },
            {
                "exception_object_id": 69859332878140,
                "id": 59,
                "trace": "actionpack (6.0.3.1) lib/action_dispatch/middleware/show_exceptions.rb:33:in `call'"
            },
            {
                "exception_object_id": 69859332878140,
                "id": 60,
                "trace": "railties (6.0.3.1) lib/rails/rack/logger.rb:37:in `call_app'"
            },
            {
                "exception_object_id": 69859332878140,
                "id": 61,
                "trace": "railties (6.0.3.1) lib/rails/rack/logger.rb:26:in `block in call'"
            },
            {
                "exception_object_id": 69859332878140,
                "id": 62,
                "trace": "activesupport (6.0.3.1) lib/active_support/tagged_logging.rb:80:in `block in tagged'"
            },
            {
                "exception_object_id": 69859332878140,
                "id": 63,
                "trace": "activesupport (6.0.3.1) lib/active_support/tagged_logging.rb:28:in `tagged'"
            },
            {
                "exception_object_id": 69859332878140,
                "id": 64,
                "trace": "activesupport (6.0.3.1) lib/active_support/tagged_logging.rb:80:in `tagged'"
            },
            {
                "exception_object_id": 69859332878140,
                "id": 65,
                "trace": "railties (6.0.3.1) lib/rails/rack/logger.rb:26:in `call'"
            },
            {
                "exception_object_id": 69859332878140,
                "id": 66,
                "trace": "actionpack (6.0.3.1) lib/action_dispatch/middleware/remote_ip.rb:81:in `call'"
            },
            {
                "exception_object_id": 69859332878140,
                "id": 67,
                "trace": "actionpack (6.0.3.1) lib/action_dispatch/middleware/request_id.rb:27:in `call'"
            },
            {
                "exception_object_id": 69859332878140,
                "id": 68,
                "trace": "rack (2.2.2) lib/rack/runtime.rb:22:in `call'"
            },
            {
                "exception_object_id": 69859332878140,
                "id": 69,
                "trace": "activesupport (6.0.3.1) lib/active_support/cache/strategy/local_cache_middleware.rb:29:in `call'"
            },
            {
                "exception_object_id": 69859332878140,
                "id": 70,
                "trace": "actionpack (6.0.3.1) lib/action_dispatch/middleware/executor.rb:14:in `call'"
            },
            {
                "exception_object_id": 69859332878140,
                "id": 71,
                "trace": "actionpack (6.0.3.1) lib/action_dispatch/middleware/static.rb:126:in `call'"
            },
            {
                "exception_object_id": 69859332878140,
                "id": 72,
                "trace": "rack (2.2.2) lib/rack/sendfile.rb:110:in `call'"
            },
            {
                "exception_object_id": 69859332878140,
                "id": 73,
                "trace": "actionpack (6.0.3.1) lib/action_dispatch/middleware/host_authorization.rb:82:in `call'"
            },
            {
                "exception_object_id": 69859332878140,
                "id": 74,
                "trace": "railties (6.0.3.1) lib/rails/engine.rb:527:in `call'"
            },
            {
                "exception_object_id": 69859332878140,
                "id": 75,
                "trace": "puma (4.3.5) lib/puma/configuration.rb:228:in `call'"
            },
            {
                "exception_object_id": 69859332878140,
                "id": 76,
                "trace": "puma (4.3.5) lib/puma/server.rb:713:in `handle_request'"
            },
            {
                "exception_object_id": 69859332878140,
                "id": 77,
                "trace": "puma (4.3.5) lib/puma/server.rb:472:in `process_client'"
            },
            {
                "exception_object_id": 69859332878140,
                "id": 78,
                "trace": "puma (4.3.5) lib/puma/server.rb:328:in `block in run'"
            },
            {
                "exception_object_id": 69859332878140,
                "id": 79,
                "trace": "puma (4.3.5) lib/puma/thread_pool.rb:134:in `block in spawn_thread'"
            }
        ],
        "Full Trace": [
            {
                "exception_object_id": 69859332878140,
                "id": 0,
                "trace": "carrierwave (2.1.0) lib/carrierwave/processing/mini_magick.rb:149:in `resize_to_fit'"
            },
            {
                "exception_object_id": 69859332878140,
                "id": 1,
                "trace": "carrierwave (2.1.0) lib/carrierwave/uploader/processing.rb:83:in `block (2 levels) in process!'"
            },
            {
                "exception_object_id": 69859332878140,
                "id": 2,
                "trace": "carrierwave (2.1.0) lib/carrierwave/uploader/processing.rb:75:in `each'"
            },
            {
                "exception_object_id": 69859332878140,
                "id": 3,
                "trace": "carrierwave (2.1.0) lib/carrierwave/uploader/processing.rb:75:in `block in process!'"
            },
            {
                "exception_object_id": 69859332878140,
                "id": 4,
                "trace": "carrierwave (2.1.0) lib/carrierwave/uploader/callbacks.rb:15:in `with_callbacks'"
            },
            {
                "exception_object_id": 69859332878140,
                "id": 5,
                "trace": "carrierwave (2.1.0) lib/carrierwave/uploader/processing.rb:74:in `process!'"
            },
            {
                "exception_object_id": 69859332878140,
                "id": 6,
                "trace": "carrierwave (2.1.0) lib/carrierwave/uploader/callbacks.rb:14:in `block in with_callbacks'"
            },
            {
                "exception_object_id": 69859332878140,
                "id": 7,
                "trace": "carrierwave (2.1.0) lib/carrierwave/uploader/callbacks.rb:14:in `each'"
            },
            {
                "exception_object_id": 69859332878140,
                "id": 8,
                "trace": "carrierwave (2.1.0) lib/carrierwave/uploader/callbacks.rb:14:in `with_callbacks'"
            },
            {
                "exception_object_id": 69859332878140,
                "id": 9,
                "trace": "carrierwave (2.1.0) lib/carrierwave/uploader/cache.rb:144:in `cache!'"
            },
            {
                "exception_object_id": 69859332878140,
                "id": 10,
                "trace": "carrierwave (2.1.0) lib/carrierwave/uploader/versions.rb:310:in `block in cache_versions!'"
            },
            {
                "exception_object_id": 69859332878140,
                "id": 11,
                "trace": "carrierwave (2.1.0) lib/carrierwave/uploader/versions.rb:308:in `each'"
            },
            {
                "exception_object_id": 69859332878140,
                "id": 12,
                "trace": "carrierwave (2.1.0) lib/carrierwave/uploader/versions.rb:308:in `cache_versions!'"
            },
            {
                "exception_object_id": 69859332878140,
                "id": 13,
                "trace": "carrierwave (2.1.0) lib/carrierwave/uploader/callbacks.rb:16:in `block in with_callbacks'"
            },
            {
                "exception_object_id": 69859332878140,
                "id": 14,
                "trace": "carrierwave (2.1.0) lib/carrierwave/uploader/callbacks.rb:16:in `each'"
            },
            {
                "exception_object_id": 69859332878140,
                "id": 15,
                "trace": "carrierwave (2.1.0) lib/carrierwave/uploader/callbacks.rb:16:in `with_callbacks'"
            },
            {
                "exception_object_id": 69859332878140,
                "id": 16,
                "trace": "carrierwave (2.1.0) lib/carrierwave/uploader/cache.rb:144:in `cache!'"
            },
            {
                "exception_object_id": 69859332878140,
                "id": 17,
                "trace": "carrierwave (2.1.0) lib/carrierwave/mounter.rb:63:in `block (2 levels) in cache'"
            },
            {
                "exception_object_id": 69859332878140,
                "id": 18,
                "trace": "carrierwave (2.1.0) lib/carrierwave/mounter.rb:176:in `handle_error'"
            },
            {
                "exception_object_id": 69859332878140,
                "id": 19,
                "trace": "carrierwave (2.1.0) lib/carrierwave/mounter.rb:47:in `block in cache'"
            },
            {
                "exception_object_id": 69859332878140,
                "id": 20,
                "trace": "carrierwave (2.1.0) lib/carrierwave/mounter.rb:46:in `map'"
            },
            {
                "exception_object_id": 69859332878140,
                "id": 21,
                "trace": "carrierwave (2.1.0) lib/carrierwave/mounter.rb:46:in `cache'"
            },
            {
                "exception_object_id": 69859332878140,
                "id": 22,
                "trace": "carrierwave (2.1.0) lib/carrierwave/mount.rb:146:in `avatar='"
            },
            {
                "exception_object_id": 69859332878140,
                "id": 23,
                "trace": "carrierwave (2.1.0) lib/carrierwave/mount.rb:373:in `avatar='"
            },
            {
                "exception_object_id": 69859332878140,
                "id": 24,
                "trace": "carrierwave (2.1.0) lib/carrierwave/orm/activerecord.rb:75:in `avatar='"
            },
            {
                "exception_object_id": 69859332878140,
                "id": 25,
                "trace": "app/controllers/v1/users_controller.rb:18:in `update'"
            },
            {
                "exception_object_id": 69859332878140,
                "id": 26,
                "trace": "actionpack (6.0.3.1) lib/action_controller/metal/basic_implicit_render.rb:6:in `send_action'"
            },
            {
                "exception_object_id": 69859332878140,
                "id": 27,
                "trace": "actionpack (6.0.3.1) lib/abstract_controller/base.rb:195:in `process_action'"
            },
            {
                "exception_object_id": 69859332878140,
                "id": 28,
                "trace": "actionpack (6.0.3.1) lib/action_controller/metal/rendering.rb:30:in `process_action'"
            },
            {
                "exception_object_id": 69859332878140,
                "id": 29,
                "trace": "actionpack (6.0.3.1) lib/abstract_controller/callbacks.rb:42:in `block in process_action'"
            },
            {
                "exception_object_id": 69859332878140,
                "id": 30,
                "trace": "activesupport (6.0.3.1) lib/active_support/callbacks.rb:135:in `run_callbacks'"
            },
            {
                "exception_object_id": 69859332878140,
                "id": 31,
                "trace": "actionpack (6.0.3.1) lib/abstract_controller/callbacks.rb:41:in `process_action'"
            },
            {
                "exception_object_id": 69859332878140,
                "id": 32,
                "trace": "actionpack (6.0.3.1) lib/action_controller/metal/rescue.rb:22:in `process_action'"
            },
            {
                "exception_object_id": 69859332878140,
                "id": 33,
                "trace": "actionpack (6.0.3.1) lib/action_controller/metal/instrumentation.rb:33:in `block in process_action'"
            },
            {
                "exception_object_id": 69859332878140,
                "id": 34,
                "trace": "activesupport (6.0.3.1) lib/active_support/notifications.rb:180:in `block in instrument'"
            },
            {
                "exception_object_id": 69859332878140,
                "id": 35,
                "trace": "activesupport (6.0.3.1) lib/active_support/notifications/instrumenter.rb:24:in `instrument'"
            },
            {
                "exception_object_id": 69859332878140,
                "id": 36,
                "trace": "activesupport (6.0.3.1) lib/active_support/notifications.rb:180:in `instrument'"
            },
            {
                "exception_object_id": 69859332878140,
                "id": 37,
                "trace": "actionpack (6.0.3.1) lib/action_controller/metal/instrumentation.rb:32:in `process_action'"
            },
            {
                "exception_object_id": 69859332878140,
                "id": 38,
                "trace": "actionpack (6.0.3.1) lib/action_controller/metal/params_wrapper.rb:245:in `process_action'"
            },
            {
                "exception_object_id": 69859332878140,
                "id": 39,
                "trace": "activerecord (6.0.3.1) lib/active_record/railties/controller_runtime.rb:27:in `process_action'"
            },
            {
                "exception_object_id": 69859332878140,
                "id": 40,
                "trace": "actionpack (6.0.3.1) lib/abstract_controller/base.rb:136:in `process'"
            },
            {
                "exception_object_id": 69859332878140,
                "id": 41,
                "trace": "actionpack (6.0.3.1) lib/action_controller/metal.rb:190:in `dispatch'"
            },
            {
                "exception_object_id": 69859332878140,
                "id": 42,
                "trace": "actionpack (6.0.3.1) lib/action_controller/metal.rb:254:in `dispatch'"
            },
            {
                "exception_object_id": 69859332878140,
                "id": 43,
                "trace": "actionpack (6.0.3.1) lib/action_dispatch/routing/route_set.rb:50:in `dispatch'"
            },
            {
                "exception_object_id": 69859332878140,
                "id": 44,
                "trace": "actionpack (6.0.3.1) lib/action_dispatch/routing/route_set.rb:33:in `serve'"
            },
            {
                "exception_object_id": 69859332878140,
                "id": 45,
                "trace": "actionpack (6.0.3.1) lib/action_dispatch/journey/router.rb:49:in `block in serve'"
            },
            {
                "exception_object_id": 69859332878140,
                "id": 46,
                "trace": "actionpack (6.0.3.1) lib/action_dispatch/journey/router.rb:32:in `each'"
            },
            {
                "exception_object_id": 69859332878140,
                "id": 47,
                "trace": "actionpack (6.0.3.1) lib/action_dispatch/journey/router.rb:32:in `serve'"
            },
            {
                "exception_object_id": 69859332878140,
                "id": 48,
                "trace": "actionpack (6.0.3.1) lib/action_dispatch/routing/route_set.rb:834:in `call'"
            },
            {
                "exception_object_id": 69859332878140,
                "id": 49,
                "trace": "rack (2.2.2) lib/rack/etag.rb:27:in `call'"
            },
            {
                "exception_object_id": 69859332878140,
                "id": 50,
                "trace": "rack (2.2.2) lib/rack/conditional_get.rb:40:in `call'"
            },
            {
                "exception_object_id": 69859332878140,
                "id": 51,
                "trace": "rack (2.2.2) lib/rack/head.rb:12:in `call'"
            },
            {
                "exception_object_id": 69859332878140,
                "id": 52,
                "trace": "activerecord (6.0.3.1) lib/active_record/migration.rb:567:in `call'"
            },
            {
                "exception_object_id": 69859332878140,
                "id": 53,
                "trace": "actionpack (6.0.3.1) lib/action_dispatch/middleware/callbacks.rb:27:in `block in call'"
            },
            {
                "exception_object_id": 69859332878140,
                "id": 54,
                "trace": "activesupport (6.0.3.1) lib/active_support/callbacks.rb:101:in `run_callbacks'"
            },
            {
                "exception_object_id": 69859332878140,
                "id": 55,
                "trace": "actionpack (6.0.3.1) lib/action_dispatch/middleware/callbacks.rb:26:in `call'"
            },
            {
                "exception_object_id": 69859332878140,
                "id": 56,
                "trace": "actionpack (6.0.3.1) lib/action_dispatch/middleware/executor.rb:14:in `call'"
            },
            {
                "exception_object_id": 69859332878140,
                "id": 57,
                "trace": "actionpack (6.0.3.1) lib/action_dispatch/middleware/actionable_exceptions.rb:17:in `call'"
            },
            {
                "exception_object_id": 69859332878140,
                "id": 58,
                "trace": "actionpack (6.0.3.1) lib/action_dispatch/middleware/debug_exceptions.rb:32:in `call'"
            },
            {
                "exception_object_id": 69859332878140,
                "id": 59,
                "trace": "actionpack (6.0.3.1) lib/action_dispatch/middleware/show_exceptions.rb:33:in `call'"
            },
            {
                "exception_object_id": 69859332878140,
                "id": 60,
                "trace": "railties (6.0.3.1) lib/rails/rack/logger.rb:37:in `call_app'"
            },
            {
                "exception_object_id": 69859332878140,
                "id": 61,
                "trace": "railties (6.0.3.1) lib/rails/rack/logger.rb:26:in `block in call'"
            },
            {
                "exception_object_id": 69859332878140,
                "id": 62,
                "trace": "activesupport (6.0.3.1) lib/active_support/tagged_logging.rb:80:in `block in tagged'"
            },
            {
                "exception_object_id": 69859332878140,
                "id": 63,
                "trace": "activesupport (6.0.3.1) lib/active_support/tagged_logging.rb:28:in `tagged'"
            },
            {
                "exception_object_id": 69859332878140,
                "id": 64,
                "trace": "activesupport (6.0.3.1) lib/active_support/tagged_logging.rb:80:in `tagged'"
            },
            {
                "exception_object_id": 69859332878140,
                "id": 65,
                "trace": "railties (6.0.3.1) lib/rails/rack/logger.rb:26:in `call'"
            },
            {
                "exception_object_id": 69859332878140,
                "id": 66,
                "trace": "actionpack (6.0.3.1) lib/action_dispatch/middleware/remote_ip.rb:81:in `call'"
            },
            {
                "exception_object_id": 69859332878140,
                "id": 67,
                "trace": "actionpack (6.0.3.1) lib/action_dispatch/middleware/request_id.rb:27:in `call'"
            },
            {
                "exception_object_id": 69859332878140,
                "id": 68,
                "trace": "rack (2.2.2) lib/rack/runtime.rb:22:in `call'"
            },
            {
                "exception_object_id": 69859332878140,
                "id": 69,
                "trace": "activesupport (6.0.3.1) lib/active_support/cache/strategy/local_cache_middleware.rb:29:in `call'"
            },
            {
                "exception_object_id": 69859332878140,
                "id": 70,
                "trace": "actionpack (6.0.3.1) lib/action_dispatch/middleware/executor.rb:14:in `call'"
            },
            {
                "exception_object_id": 69859332878140,
                "id": 71,
                "trace": "actionpack (6.0.3.1) lib/action_dispatch/middleware/static.rb:126:in `call'"
            },
            {
                "exception_object_id": 69859332878140,
                "id": 72,
                "trace": "rack (2.2.2) lib/rack/sendfile.rb:110:in `call'"
            },
            {
                "exception_object_id": 69859332878140,
                "id": 73,
                "trace": "actionpack (6.0.3.1) lib/action_dispatch/middleware/host_authorization.rb:82:in `call'"
            },
            {
                "exception_object_id": 69859332878140,
                "id": 74,
                "trace": "railties (6.0.3.1) lib/rails/engine.rb:527:in `call'"
            },
            {
                "exception_object_id": 69859332878140,
                "id": 75,
                "trace": "puma (4.3.5) lib/puma/configuration.rb:228:in `call'"
            },
            {
                "exception_object_id": 69859332878140,
                "id": 76,
                "trace": "puma (4.3.5) lib/puma/server.rb:713:in `handle_request'"
            },
            {
                "exception_object_id": 69859332878140,
                "id": 77,
                "trace": "puma (4.3.5) lib/puma/server.rb:472:in `process_client'"
            },
            {
                "exception_object_id": 69859332878140,
                "id": 78,
                "trace": "puma (4.3.5) lib/puma/server.rb:328:in `block in run'"
            },
            {
                "exception_object_id": 69859332878140,
                "id": 79,
                "trace": "puma (4.3.5) lib/puma/thread_pool.rb:134:in `block in spawn_thread'"
            }
        ]
    }
}
```

**Comment by kaspergrubbe** [comment]
Hi, I've had a quick look at the carrierwave code:

https://github.com/carrierwaveuploader/carrierwave/blob/v2.1.0/lib/carrierwave/processing/mini_magick.rb#L134-L156

It doesn't look like the code even hits Minimagick, so it must be a bug in Carrierwave.

**Comment by Sakaki-Ya** [comment]
I'll post it again in the Carrierwave issue as a bug report.
Thank you for looking into it.
