### ISSUE TITLE
Failing spec on master: `Date:create` is not consistently present in ImageMagick v6.9.13-11

### ISSUE THREAD

**Issue by tagliala** [minimagick/minimagick#562]
Hi, I'm attempting to move the CI on GitHub Actions, because at the moment it uses Travis which is broken

I'm having a failing spec on my local machine (which is also present against ImageMagick v6 on GitHub runners): https://github.com/tagliala/minimagick/actions/runs/9371113356/job/25799666085#step:5:442

```
$ convert --version
Version: ImageMagick 6.9.13-11 Q16 x86_64 18407 https://legacy.imagemagick.org
```

https://github.com/minimagick/minimagick/blob/862ab75e0117784f8e1138f2f4d2a5416a1a3f5b/spec/lib/mini_magick/image_spec.rb#L487

```
$ rspec ./spec/lib/mini_magick/image_spec.rb[1:1:20:2:1]
Run options: include {:focus=>true, :ids=>{"./spec/lib/mini_magick/image_spec.rb"=>["1:1:20:2:1"]}}

With ImageMagick7
  MiniMagick::Image
    #details
      when verbose information includes an empty line
[MiniMagick] MiniMagick::Image#details has been deprecated, as it was causing too many parsing errors. You should use MiniMagick::Image#data instead, which differs in a way that the keys are in camelcase.
        skips the empty line (FAILED - 1)

Failures:

  1) With ImageMagick7 MiniMagick::Image#details when verbose information includes an empty line skips the empty line
     Failure/Error: expect(subject.details).to have_key("Date:create")
       expected #has_key?("Date:create") to return true, got false
     # ./spec/lib/mini_magick/image_spec.rb:487:in `block (6 levels) in <top (required)>'
     # ~/.rvm/gems/ruby-3.3.2/gems/webmock-3.23.1/lib/webmock/rspec.rb:39:in `block (2 levels) in <top (required)>'

Finished in 0.06867 seconds (files took 0.32061 seconds to load)
1 example, 1 failure

Failed examples:

rspec ./spec/lib/mini_magick/image_spec.rb[1:1:20:2:1] # With ImageMagick7 MiniMagick::Image#details when verbose information includes an empty line skips the empty line
```

```
(byebug) described_class.new(image_path(:empty_identify_line)).details.keys.sort
["Artifacts", "Background color", "Base filename", "Border color", "Channel depth", "Channel statistics", "Channels", "Chromaticity", "Class", "Colorspace", "Compose", "Compression", "Depth", "Dispose", "Elapsed time", "Endianness", "Filename", "Filesize", "Format", "Gamma", "Geometry", "Image statistics", "Intensity", "Interlace", "Iterations", "Matte color", "Mime type", "Number pixels", "Orientation", "Page geometry", "Permissions", "Pixel cache type", "Pixels per second", "Properties", "Rendering intent", "Tainted", "Transparent color", "Type", "Units", "User time", "Version"]
```

The metadata is present in `properties`, like in ImageMagick v7:

```
(byebug) MiniMagick.imagemagick7?
false

(byebug) described_class.new(image_path(:empty_identify_line)).details['Properties'].keys.sort
["comment", "date:create", "date:modify", "date:timestamp", "png:IHDR.bit-depth-orig", "png:IHDR.bit_depth", "png:IHDR.color-type-orig", "png:IHDR.color_type", "png:IHDR.interlace_method", "png:IHDR.width,height", "png:bKGD", "png:cHRM", "png:gAMA", "png:text", "signature"]
```

**Comment by janko** [comment]
Thanks for working on GitHub actions. I think we can just skip the assertion for IM6 in this case.

BTW, I tried adding GitHub actions in https://github.com/minimagick/minimagick/pull/535, but it seems like I don't have enough permissions on the repo. I tried getting them from the original owner in the past, but I received no response 🤷🏻‍♂️

**Comment by tagliala** [comment]
> I fixed this now in #563, after I got the desired repo permissions. BTW, I wasn't able to install IM7 in GitHub Actions, let me know if you've found a way 🙂

Hi @janko,

there is an experimental run here:

https://github.com/tagliala/minimagick/actions/runs/9423216627/job/25961154656#step:8:257

There is just a single spec failing, but the action should be improved:

```
  1) MiniMagick::Image#size returns the correct value even if the log contains unit prefixes
     Failure/Error: fail MiniMagick::Error, "`#{command.join(" ")}` failed with status: #{status.inspect} and error:\n#{stderr}"

     MiniMagick::Error:
       `magick identify -format %m %w %h %b spec/fixtures/large_webp.webp[0]` failed with status: 1 and error:
       identify: delegate failed `'dwebp' -pam '%i' -o '%o'' @ error/delegate.c/InvokeDelegate/1911.
       identify: unable to open file '/tmp/magick-6iQVfa0S0f0E9qK5odCsVuZM6FWWHGl8': No such file or directory @ error/constitute.c/ReadImage/785.
     # ./lib/mini_magick/shell.rb:17:in `run'
     # ./lib/mini_magick/tool.rb:92:in `call'
     # ./lib/mini_magick/tool.rb:38:in `new'
     # ./lib/mini_magick/image/info.rb:183:in `identify'
     # ./lib/mini_magick/image/info.rb:127:in `raw'
     # ./lib/mini_magick/image/info.rb:35:in `[]'
     # ./lib/mini_magick/image/info.rb:45:in `block in cheap_info'
     # ./lib/mini_magick/image/info.rb:44:in `fetch'
     # ./lib/mini_magick/image/info.rb:44:in `cheap_info'
     # ./lib/mini_magick/image/info.rb:17:in `[]'
     # ./lib/mini_magick/image.rb:145:in `block in attribute'
     # ./spec/lib/mini_magick/image_spec.rb:425:in `block (3 levels) in <top (required)>'
     # ./vendor/bundle/ruby/3.3.0/gems/webmock-3.23.1/lib/webmock/rspec.rb:39:in `block (2 levels) in <top (required)>'
```

Maybe it is missing some libraries?

- It would be better to find a binary artifact, maybe in some apt source I'm not aware of
- Compilation takes 5 minutes. If IM7 should be compiled, then artifacts should be cached, but I have not too much experience on caching artifacts (they are several files in several directories I guess. I should understand what "make install" exactly does)
-

**Comment by tagliala** [comment]
Yes, it was the missing webp.

CI passing against ImageMagick v7: https://github.com/tagliala/minimagick/actions/runs/9423347146/job/25961537610

Do you know the list of executables that we need to cache?

**Comment by tagliala** [comment]
Yes, it was the missing webp.

CI passing against ImageMagick v7: https://github.com/tagliala/minimagick/actions/runs/9423347146/job/25961537610

Do you know the list of executables that we need to cache?

**Comment by janko** [comment]
For IM7 only `magick`, I believe. Not sure if it's worth slowing down CI for IM7, though, I didn't like how slow Travis CI was due to building IM7. I just assumed GH actions will already have IM7, but I'm ready to accept to test just on IM6.
