### ISSUE TITLE
Check error when building with ImageMagick 7.1.11-35

### ISSUE THREAD

**Issue by fundawang** [minimagick/minimagick#575]
Hello, I'm building minimagick 5.0.0 with ImageMagick 7.1.11-35, it failed with check:
```
  1) MiniMagick::Image equivalence is not #== nor #eql? to an instance of a different image
     Failure/Error: fail MiniMagick::Error, "`#{command.join(" ")}` failed with status: #{status.inspect} and error:\n#{stderr}"

     MiniMagick::Error:
       `magick mogrify -to-ary spec/fixtures/default.jpg` failed with status: 1 and error:
       mogrify: unrecognized option `-to-ary' @ error/mogrify.c/MogrifyImageCommand/6405.
     # ./lib/mini_magick/shell.rb:20:in `run'
     # ./lib/mini_magick/tool.rb:85:in `call'
     # ./lib/mini_magick/tool.rb:35:in `new'
     # ./lib/mini_magick.rb:27:in `block (2 levels) in <module:MiniMagick>'
     # ./lib/mini_magick/image.rb:561:in `mogrify'
     # ./lib/mini_magick/image.rb:463:in `method_missing'
     # ./spec/lib/mini_magick/image_spec.rb:172:in `block (3 levels) in <top (required)>'
     # /usr/share/gems/gems/webmock-3.18.1/lib/webmock/rspec.rb:37:in `block (2 levels) in <top (required)>'
```

Is that something wrong with it?

**Comment by fundawang** [comment]
Full log here:
https://[eur.openeuler.openatom.cn/results/fundawang/test_rebuild/openeuler-24.03_LTS-aarch64/00094512-rubygem-mini_magick/builder-live.log.gz](https://eur.openeuler.openatom.cn/results/fundawang/test_rebuild/openeuler-24.03_LTS-aarch64/00094512-rubygem-mini_magick/builder-live.log.gz)

**Comment by fundawang** [comment]
When building 4.13.2:
https://eur.openeuler.openatom.cn/results/fundawang/test_rebuild/openeuler-24.03_LTS-x86_64/00094513-rubygem-mini_magick/builder-live.log.gz

**Comment by janko** [comment]
Could you give me a minimal self-contained example that reproduces the error?

**Comment by fundawang** [comment]
> Could you give me a minimal self-contained example that reproduces the error?
As mentioned in the first commnet:
```
+ rspec spec
`did_you_mean' was not loaded.

MiniMagick::Image
  has attributes
  generates attributes of layers
  changes colorspace when called with an argument
  changes size when called with an argument
  .read
    reads image from String
    reads image from StringIO
    reads image from tempfile
  .import_pixels
    can import pixels with default format
    can import pixels with custom format
  .open
    makes a copy of the image
    accepts a Pathname
    accepts a non-ascii filename
    loads a remote image
    doesn't allow remote shell execution
    accepts open-uri options
    strips out colons from URL
    does not mistake a path with a colon for a URI schema
  .create
    creates an image
    when a tmpdir is configured
      uses the tmpdir to create the file
  #initialize
    initializes a new image
    accepts a Pathname
    accepts a block which it passes on to #combine_options
  equivalence
    is #== and #eql? to itself
    is #== and #eql? to an instance of the same image
    is not #== nor #eql? to an instance of a different image (FAILED - 1)

Failures:

  1) MiniMagick::Image equivalence is not #== nor #eql? to an instance of a different image
     Failure/Error: fail MiniMagick::Error, "`#{command.join(" ")}` failed with status: #{status.inspect} and error:\n#{stderr}"

     MiniMagick::Error:
       `magick mogrify -to-ary spec/fixtures/default.jpg` failed with status: 1 and error:
       mogrify: unrecognized option `-to-ary' @ error/mogrify.c/MogrifyImageCommand/6405.
     # ./lib/mini_magick/shell.rb:20:in `run'
     # ./lib/mini_magick/tool.rb:85:in `call'
     # ./lib/mini_magick/tool.rb:35:in `new'
     # ./lib/mini_magick.rb:27:in `block (2 levels) in <module:MiniMagick>'
     # ./lib/mini_magick/image.rb:561:in `mogrify'
     # ./lib/mini_magick/image.rb:463:in `method_missing'
     # ./spec/lib/mini_magick/image_spec.rb:172:in `block (3 levels) in <top (required)>'
     # /usr/share/gems/gems/webmock-3.18.1/lib/webmock/rspec.rb:37:in `block (2 levels) in <top (required)>'
```
It is very strange that there is no 'to-ary' in every pieces of minimagick, I don't know where it comes from.

**Comment by janko** [comment]
Yes, that's very strange indeed. I don't know what is trying to call `#to_ary`. Could you try running `bundle exec rspec` instead, to rule out that was the issue?

**Comment by fundawang** [comment]
> is #== and #eql? to itself
>     is #== and #eql? to an instance of the same image
>     is not #== nor #eql? to an instance of a different image (FAILED - 1)
> 
> Failures:
> 
>   1) MiniMagick::Image equivalence is not #== nor #eql? to an instance of a different image
>      Failure/Error: fail MiniMagick::Error, "`#{command.join(" ")}` failed with status: #{status.inspect} and error:\n#{stderr}"
> 
>      MiniMagick::Error:
>        `magick mogrify -to-ary spec/fixtures/default.jpg` failed with status: 1 and error:
>        mogrify: unrecognized option `-to-ary' @ error/mogrify.c/MogrifyImageCommand/6405.
>      # ./lib/mini_magick/shell.rb:20:in `run'
>      # ./lib/mini_magick/tool.rb:85:in `call'
>      # ./lib/mini_magick/tool.rb:35:in `new'
>      # ./lib/mini_magick.rb:27:in `block (2 levels) in <module:MiniMagick>'
>      # ./lib/mini_magick/image.rb:561:in `mogrify'
>      # ./lib/mini_magick/image.rb:463:in `method_missing'
>      # ./spec/lib/mini_magick/image_spec.rb:172:in `block (3 levels) in <top (required)>'
>      # /usr/share/gems/gems/webmock-3.18.1/lib/webmock/rspec.rb:37:in `block (2 levels) in <top (required)>'
```
+ bundle exec rspec
`did_you_mean' was not loaded.
bundler: failed to load command: rspec (/usr/bin/rspec)
/usr/share/gems/gems/bundler-2.4.10/lib/bundler/resolver.rb:290:in `raise_not_found!': Could not find gem 'rspec (~> 3.5.0)' in locally installed gems. (Bundler::GemNotFound)
```
It is still very strange that rspec 3.12.0 was already there.

FYI, when builiding minimagick 4.13.2, it produces following output:
```
+ rspec spec
`did_you_mean' was not loaded.

MiniMagick::Configuration
  #configure
    yields self
  #cli
    can be assigned
    returns :imagemagick if #processor is mogrify
    returns :graphicsmagick if #processor is gm
    raises an error if #processor could not be found
  #cli=
    raises an error when set to an invalid value
  #cli_prefix
    can be assigned
  #processor
    assigns 'mogrify' if ImageMagick 6 is available, and others are not
    assigns 'gm' if others are not available
    assigns 'magick' if ImageMagick 7 available
    returns nil if neither ImageMagick nor GraphicsMagick are available
  #processor=
    raises an error when set to an invalid value

MiniMagick::Image
[MiniMagick] MiniMagick::Image#mime_type has been deprecated, because it wasn't returning correct result for all formats ImageMagick supports. Unfortunately, returning the correct MIME type would be very slow, because it would require ImageMagick to read the whole file. It's better to use Marcel and MimeMagic gems, which are able to determine the MIME type just from the image header.
  has attributes
  generates attributes of layers
  changes colorspace when called with an argument
  changes size when called with an argument
  .read
    reads image from String
    reads image from StringIO
    reads image from tempfile
  .import_pixels
    can import pixels with default format
    can import pixels with custom format
  .open
    makes a copy of the image
    accepts a Pathname
    accepts a non-ascii filename
    loads a remote image
    doesn't allow remote shell execution
    accepts open-uri options
    strips out colons from URL
    validates the image
    does not mistake a path with a colon for a URI schema
  .create
    creates an image
    validates the image if validation is set
    doesn't validate image if validation is disabled
    when a tmpdir is configured
      uses the tmpdir to create the file
  #initialize
    initializes a new image
    accepts a Pathname
    accepts a block which it passes on to #combine_options
  equivalence
    is #== and #eql? to itself
    is #== and #eql? to an instance of the same image
    is not #== nor #eql? to an instance of a different image (FAILED - 1)

Failures:

  1) MiniMagick::Image equivalence is not #== nor #eql? to an instance of a different image
     Failure/Error: expect(image).not_to eq(other_image)

       expected: value != #<MiniMagick::Image:0x00007fd985db5838 @path="spec/fixtures/exif.jpg", @tempfile=nil, @info=#<MiniMag...495991b7852b855", "signature"=>"e3b0c44298fc1c149afbf4c8996fb92427ae41e4649b934ca495991b7852b855"}>>
            got: #<MiniMagick::Image:0x00007fd985db5a18 @path="spec/fixtures/default.jpg", @tempfile=nil, @info=#<Mini...495991b7852b855", "signature"=>"e3b0c44298fc1c149afbf4c8996fb92427ae41e4649b934ca495991b7852b855"}>>

       (compared using ==)

       Diff:


       @@ -1,12 +1,12 @@
       -#<MiniMagick::Image:0x00007fd985db5838
       +#<MiniMagick::Image:0x00007fd985db5a18
         @info=
       -  #<MiniMagick::Image::Info:0x00007fd985db5810
       +  #<MiniMagick::Image::Info:0x00007fd985db59f0
           @info=
            {"raw:%#"=>
              "e3b0c44298fc1c149afbf4c8996fb92427ae41e4649b934ca495991b7852b855",
             "signature"=>
              "e3b0c44298fc1c149afbf4c8996fb92427ae41e4649b934ca495991b7852b855"},
       -   @path="spec/fixtures/exif.jpg">,
       - @path="spec/fixtures/exif.jpg",
       +   @path="spec/fixtures/default.jpg">,
       + @path="spec/fixtures/default.jpg",
         @tempfile=nil>
     # ./spec/lib/mini_magick/image_spec.rb:189:in `block (3 levels) in <top (required)>'
     # /usr/share/gems/gems/webmock-3.18.1/lib/webmock/rspec.rb:37:in `block (2 levels) in <top (required)>'

Finished in 0.3792 seconds (files took 0.31193 seconds to load)
40 examples, 1 failure

Failed examples:

rspec ./spec/lib/mini_magick/image_spec.rb:188 # MiniMagick::Image equivalence is not #== nor #eql? to an instance of a different image
```

**Comment by fundawang** [comment]
And when building 4.13.2 with earlier verison of imagemagick (7.1.1-15), all goes well.

**Comment by janko** [comment]
ImageMagick 7.1.11-35 hasn't yet arrived to Homebrew, so I cannot install it and test it out at the moment.

**Comment by janko** [comment]
It arrived to Homebrew, so I was able to install it and reproduce the error.

The root cause is that this version of ImageMagick returns the same signature for every image (`magick identify -format "%#" <image.jpg>`), so any `MiniMagick::Image` is equal to each other.

This causes an RSpec assertion failure, and in the process of generating the error message, it tries to call `#to_ary` on the `MiniMagick::Image`. This is because Ruby for some reason implicitly calls `#to_ary` on `[image1, image2].flatten(1)`. The reason seems to be removal of `#respond_to_missing?`, I will likely add it back for backwards compatibility.
