### ISSUE TITLE
PDF get garbage collected whilst processing pages

### ISSUE THREAD

**Issue by phantomwhale** [minimagick/minimagick#580]
## Background 
I've been extracting a 50+ page PDF (~300MB) into page images

The following works (using IM7):
`magick -units PixelsPerInch -density 300 ./input.pdf extracts/page.jpg`

## Issue 

The following fails consistently after 10 pages (using IM7 + latest mini_magick release)
```ruby
  MiniMagick.logger.level = Logger::DEBUG
  MiniMagick::Image.open(IN_FILE).pages.each_with_index do |page, index|
    extract_name = "./extracts/page-#{index.to_s.rjust(3, '0')}.jpg"
    MiniMagick.convert do |convert|
      convert.density 300
      convert << page.path
      convert << extract_name
    end
  end
```

I see the following in the logs:

```
D, [2024-10-18T16:57:34.847779 #8741] DEBUG -- : [1.95s] magick -density 300 /var/folders/89/062y0s350f11xcwnghj729qr0000gn/T/mini_magick20241018-8741-dtvvav.pdf[10] ./extracts/page-010.jpg
Writing page 11 to ./extracts/page-011.jpg
D, [2024-10-18T16:57:34.862342 #8741] DEBUG -- : [0.01s] magick -density 300 /var/folders/89/062y0s350f11xcwnghj729qr0000gn/T/mini_magick20241018-8741-dtvvav.pdf[11] ./extracts/page-011.jpg
bundler: failed to load command: ./format-booklet-to-print.rb (./format-booklet-to-print.rb)
/Users/ben/.gem/ruby/3.3.5/gems/mini_magick-5.0.1/lib/mini_magick/shell.rb:20:in `run': `magick -density 300 /var/folders/89/062y0s350f11xcwnghj729qr0000gn/T/mini_magick20241018-8741-dtvvav.pdf[11] ./extracts/extract-011.jpg` failed with status: 1 and error: (MiniMagick::Error)
magick: unable to open image '/var/folders/89/062y0s350f11xcwnghj729qr0000gn/T/mini_magick20241018-8741-dtvvav.pdf': No such file or directory @ error/blob.c/OpenBlob/3596.

	from /Users/ben/.gem/ruby/3.3.5/gems/mini_magick-5.0.1/lib/mini_magick/tool.rb:85:in `call'
	from /Users/ben/.gem/ruby/3.3.5/gems/mini_magick-5.0.1/lib/mini_magick/tool.rb:35:in `new'
	from /Users/ben/.gem/ruby/3.3.5/gems/mini_magick-5.0.1/lib/mini_magick.rb:27:in `block (2 levels) in <module:MiniMagick>'
```

## Workaround 

By surrounding the above script with `GC.disable` and `GC.enable` this works without the error happening

**Comment by janko** [comment]
`MiniMagick::Image.open` returns a `MiniMagick::Image` object that holds a reference to a `Tempfile` object. As long as you're hold a reference to the `MiniMagick::Image` object, the `Tempfile` object cannot be garbage collected.

In your example, you didn't keep a reference before you started iterating, so Ruby deems the `Tempfile` safe to garbage-collect. It should be enough to just assign the image into a local variable:

```rb
image = MiniMagick::Image.open(IN_FILE) # keep the reference
image.pages.each_with_index do |page, index|
  # ...
end
```
