### ISSUE TITLE
import_pixels gives "mogrify: unable to open image (/tmp/mini_magick...png)"

### ISSUE THREAD

**Issue by jewel** [minimagick/minimagick#84]
I ran into trouble decoding raw image data:

``` ruby
i = MiniMagick::Image.import_pixels 0.chr * 64, 4, 4, 4, 'rgba'
i.resize "2x2"
```

This gives the following error:

```
MiniMagick::Error: Command ("mogrify -resize "2x2" /tmp/mini_magick20120503-9816-soa1i9.png") failed: {:status_code=>1, :output=>"mogrify: unable to open image `/tmp/mini_magick20120503-9816-soa1i9.png':  @ error/blob.c/OpenBlob/2498.\nmogrify: unable to open file `/tmp/mini_magick20120503-9816-soa1i9.png' @ error/png.c/ReadPNGImage/3072.\n"}
    from /home/jewel/.rvm/gems/ruby-1.9.3-p194/gems/mini_magick-3.4/lib/mini_magick.rb:417:in `run'
    from /home/jewel/.rvm/gems/ruby-1.9.3-p194/gems/mini_magick-3.4/lib/mini_magick.rb:362:in `combine_options'
    from /home/jewel/.rvm/gems/ruby-1.9.3-p194/gems/mini_magick-3.4/lib/mini_magick.rb:341:in `method_missing'
    from (irb):21
    from /home/jewel/.rvm/rubies/ruby-1.9.3-p194/bin/irb:16:in `<main>'
```

However, it works fine if "pam" is passed as an additional argument.  (This might be a better default value than PNG anyway.)

This is on Ubuntu natty, ruby 1.9.3p194, ImageMagick 6.6.2-6 (from apt).

**Comment by picrypto** [comment]
How can i fix this?! ;)

**Comment by justi** [comment]
You can create your own temp file
tmp_file = Tempfile.new("some_name")
and save them the result
